"""Emit SQL that backfills `llm_usage_events` from the pre-existing history.

    python scripts/backfill_llm_usage.py > backfill.sql
    psql "$SUPABASE_DB_URL" -v ON_ERROR_STOP=1 --single-transaction -f backfill.sql

Why generate the SQL instead of hand-writing it: the feature taxonomy lives in
`app.usage_context._AGENT_FEATURE`, and a hand-written CASE would silently drift
from it the first time an agent is added or remapped. Here the CASE is rendered
FROM that dict, so the backfill and the live metering can never disagree about
what "prd" or "ingest:github" means.

Two disjoint sources (verified against the live DB 2026-07-25 — no design-agent
rows appear in `agent_decision_log`, because the design agent calls its own
client factory rather than the gateway, so nothing is double-counted):

  * `agent_decision_log`         — decision_type 'llm_call' (Anthropic) and
                                   'embedding' (OpenAI). Tokens + cost live in
                                   the `factors` JSONB.
  * `design_agent_usage_events`  — one row per prototype generation/iteration,
                                   with token columns of its own.

Fidelity caveats, deliberate and visible in the data rather than hidden:

  * `key_mode` is 'unknown'. Which key paid was never recorded historically, and
    inferring it from today's `companies.llm_api_key_encrypted` would be wrong
    for every row written before that key was added. 'unknown' is the honest
    value — and doubles as the idempotency marker, since live metering always
    writes 'customer' or 'platform' (see the DELETE below).
  * `cache_creation_input_tokens` is 0. The gateway's `factors` recorded
    cache_READ only. The stored `cost_usd` DID include cache-write spend, so the
    money is right even though that one token column is under-reported.
  * `user_id` is null — the gateway never knew the acting user.
  * Only terminal design-agent rows are carried over; `status='started'` rows are
    runs that never reported a result and have no tokens to report.
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app.usage_context import _AGENT_FEATURE, Feature  # noqa: E402


def _sql_str(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def _feature_case() -> str:
    """Render `feature_for_agent` as a SQL CASE over `agent_decision_log.agent`."""
    lines = [
        # Prefix rule first — it must win over any exact match.
        f"      when l.agent like 'ingest:%' then {_sql_str(Feature.KG_INGEST)}",
    ]
    for agent, feature in sorted(_AGENT_FEATURE.items()):
        lines.append(
            f"      when l.agent = {_sql_str(agent)} then {_sql_str(feature)}"
        )
    # Same fallback as the Python: an unmapped agent keeps its own name rather
    # than collapsing into 'unattributed'.
    lines.append("      else l.agent")
    return "    case\n" + "\n".join(lines) + "\n    end"


TEMPLATE = """\
-- Backfill of llm_usage_events from historical telemetry.
-- GENERATED by backend/scripts/backfill_llm_usage.py — do not edit by hand.
-- Re-runnable: the DELETE below removes only previously-backfilled rows.

begin;

-- Idempotency. Live metering always records a real key_mode ('customer' or
-- 'platform'), so 'unknown' identifies exactly the rows this script wrote.
delete from llm_usage_events where key_mode = 'unknown';

-- 1. Gateway + embeddings history (agent_decision_log).
insert into llm_usage_events (
  company_id, user_id, feature, operation, provider, model, key_mode,
  input_tokens, output_tokens, cache_creation_input_tokens,
  cache_read_input_tokens, est_cost_usd, latency_ms, status, created_at
)
select
  l.enterprise_id::text,
  null,
{feature_case},
  nullif(l.factors->>'purpose', ''),
  case when l.decision_type = 'embedding' then 'openai' else 'anthropic' end,
  l.model,
  'unknown',
  coalesce((l.factors->>'input_tokens')::bigint, 0),
  coalesce((l.factors->>'output_tokens')::bigint, 0),
  0,
  coalesce((l.factors->>'cache_read_input_tokens')::bigint, 0),
  (l.factors->>'cost_usd')::numeric,
  (l.factors->>'latency_ms')::int,
  'succeeded',
  l."timestamp"
from agent_decision_log l
where l.decision_type in ('llm_call', 'embedding');

-- 2. Prototype generation/iteration history (design_agent_usage_events).
insert into llm_usage_events (
  company_id, user_id, feature, operation, provider, model, key_mode,
  input_tokens, output_tokens, cache_creation_input_tokens,
  cache_read_input_tokens, est_cost_usd, latency_ms, status, created_at
)
select
  d.workspace_id,
  null,
  {design_feature},
  case when d.kind = 'full_generation' then 'generate' else 'iterate' end,
  'anthropic',
  d.model,
  'unknown',
  coalesce(d.input_tokens, 0),
  coalesce(d.output_tokens, 0),
  coalesce(d.cache_creation_input_tokens, 0),
  coalesce(d.cache_read_input_tokens, 0),
  d.est_cost_usd,
  null,
  d.status,
  coalesce(d.completed_at, d.created_at)
from design_agent_usage_events d
where d.status in ('succeeded', 'failed');

commit;

-- Verification
select
  count(*)                                   as backfilled_rows,
  count(distinct company_id)                 as companies,
  round(sum(est_cost_usd)::numeric, 2)       as est_usd,
  min(created_at)::date                      as first_day,
  max(created_at)::date                      as last_day
from llm_usage_events
where key_mode = 'unknown';
"""


def main() -> None:
    sys.stdout.write(
        TEMPLATE.format(
            feature_case=_feature_case(),
            design_feature=_sql_str(Feature.DESIGN_AGENT),
        )
    )


if __name__ == "__main__":
    main()
