-- Sprntly Pipeline Tables
-- Run this in Supabase SQL Editor (https://supabase.com/dashboard → SQL Editor)

-- 1. Knowledge entities: LLM-extracted entities from corpus
CREATE TABLE IF NOT EXISTS knowledge_entities (
    id          bigint generated by default as identity primary key,
    dataset     text not null,
    entity_type text not null,
    name        text not null,
    attributes  jsonb not null default '{}',
    source_file text,
    confidence  real default 0.5,
    created_at  timestamptz default now(),
    updated_at  timestamptz default now(),
    unique(dataset, entity_type, name)
);

-- 2. Knowledge relationships: entity-to-entity edges
CREATE TABLE IF NOT EXISTS knowledge_relationships (
    id                bigint generated by default as identity primary key,
    dataset           text not null,
    source_entity_id  bigint references knowledge_entities(id) on delete cascade,
    target_entity_id  bigint references knowledge_entities(id) on delete cascade,
    relation          text not null,
    weight            real default 1.0,
    evidence          text,
    created_at        timestamptz default now(),
    unique(dataset, source_entity_id, target_entity_id, relation)
);

-- 3. Pipeline runs: audit log for orchestration runs
CREATE TABLE IF NOT EXISTS pipeline_runs (
    id            bigint generated by default as identity primary key,
    dataset       text not null,
    trigger       text not null default 'scheduled',
    status        text not null default 'running',
    stages        jsonb not null default '{}',
    started_at    timestamptz default now(),
    completed_at  timestamptz,
    error         text
);

-- 4. PRD patches (needed for GET /v1/prd/{id} — was missing)
CREATE TABLE IF NOT EXISTS prd_patches (
    id            bigint generated by default as identity primary key,
    prd_id        bigint not null,
    prototype_id  bigint not null,
    workspace_id  text not null,
    rationale     text not null,
    patch_md      text not null,
    status        text not null default 'pending'
                  check (status in ('pending', 'applied', 'rejected')),
    created_at    timestamptz default now(),
    resolved_at   timestamptz
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_ke_dataset ON knowledge_entities(dataset);
CREATE INDEX IF NOT EXISTS idx_kr_dataset ON knowledge_relationships(dataset);
CREATE INDEX IF NOT EXISTS idx_pr_dataset ON pipeline_runs(dataset, started_at desc);
CREATE INDEX IF NOT EXISTS idx_pp_prd ON prd_patches(prd_id, status);
