"""Tests for app.prd_runner — the SPLIT PRD generation.

The human PRD (Part A) and the machine-readable Implementation Spec (Part B) are
now generated by two SEPARATE flows:

  - `generate_prd` / `_run_sync` generate ONLY the human PRD via the `prd-author`
    skill and store it in payload_md. They do NOT produce or trigger Part B.
  - `ensure_impl_spec` generates Part B ON DEMAND via the `implementation-spec`
    skill (fed the finished human PRD), caches it in `llm_part` keyed to the
    human PRD's content hash, and is idempotent: a re-send reuses the cache;
    editing the human PRD invalidates it so the next send regenerates.

These tests mock at the gateway/llm seam: most patch `prd_runner.llm_call`; a
couple let the REAL gateway run and patch `app.llm.call_md` to assert the
METHOD (prd-author for the PRD, implementation-spec for the spec) reaches the
prompt.

New rows are written with variant='v2' by the route; the runner itself
produces the human PRD and calls `complete_prd` against the existing row.
"""
from __future__ import annotations

import asyncio

import pytest

from app import prd_runner
from app.graph.gateway import LLMResult


def _seed_corpus(data_dir, dataset="asurion", body="corpus body"):
    ds = data_dir / dataset
    ds.mkdir(exist_ok=True)
    (ds / "a.md").write_text(body)


def _seed_brief(db_mod, dataset="asurion", insights=None):
    if insights is None:
        insights = [{"title": "Insight A", "subtitle": "behaviour"}]
    payload = {
        "summary_headline": "stub",
        "insights": insights,
        "_schema_version": 1,
    }
    return db_mod.save_brief(
        dataset=dataset, week_label="Week of stub", payload=payload, schema_version=1
    )


def _llm_result(output, model="claude-sonnet-4-6", prompt_version="prd-author-v2"):
    return LLMResult(
        output=output, model=model, prompt_version=prompt_version,
        input_tokens=10, output_tokens=5, cache_read_input_tokens=0,
        cache_creation_input_tokens=0, cost_usd=0.001, latency_ms=5,
        stop_reason="end_turn",
    )


_PART_A = (
    "# Surface — Ship the thing\n\n"
    "# Part A — Product Requirements Document (human-readable)\n"
    "## 1. Problem & evidence\nUsers can't X.\n"
)
_PART_B = (
    "# Implementation Spec\n"
    "## B0. Available artifacts\nWHEN x THE SYSTEM SHALL y.\n"
)


def _part_a_mock(part_a=_PART_A, captured=None):
    """A `llm_call` stub that records each call's kwargs and returns Part A.

    Records the call so a test can assert the human-PRD flow makes exactly ONE
    call and NEVER a Part-B (implementation-spec) call.
    """
    captured = [] if captured is None else captured

    def _call(**kwargs):
        captured.append(kwargs)
        return _llm_result(part_a)

    return _call, captured


def _start_prd(db_mod, brief_id, title="t", insight_index=0):
    return db_mod.start_prd(
        brief_id=brief_id, insight_index=insight_index, title=title,
        template_version=1, variant="v2",
    )


# ── human PRD: Part A only, never triggers Part B ────────────────────────────

def test_run_sync_makes_one_llm_call_for_human_prd(isolated_settings, monkeypatch):
    """The human-PRD flow issues exactly ONE gateway call — the prd-author call.
    It must NOT also issue an implementation-spec (Part B) call."""
    _seed_corpus(isolated_settings["data_dir"])
    db_mod = isolated_settings["db"]
    brief_id = _seed_brief(db_mod)
    prd_id = _start_prd(db_mod, brief_id)

    call, captured = _part_a_mock()
    monkeypatch.setattr(prd_runner, "llm_call", call)
    prd_runner._run_sync(prd_id, brief_id, 0)

    assert len(captured) == 1
    assert captured[0]["purpose"] == "generate_prd_part_a"
    assert captured[0]["skill"] == "prd-author"
    # No implementation-spec call was made.
    assert all(c["skill"] != "implementation-spec" for c in captured)


def test_run_sync_stores_only_human_prd_no_llm_part(isolated_settings, monkeypatch):
    """Part A → payload_md; llm_part stays empty (Part B is on demand, not now)."""
    _seed_corpus(isolated_settings["data_dir"])
    db_mod = isolated_settings["db"]
    brief_id = _seed_brief(db_mod)
    prd_id = _start_prd(db_mod, brief_id)

    call, _ = _part_a_mock()
    monkeypatch.setattr(prd_runner, "llm_call", call)
    prd_runner._run_sync(prd_id, brief_id, 0)

    row = db_mod.get_prd(prd_id)
    assert row["status"] == "ready"
    assert "Part A — Product Requirements Document" in row["payload_md"]
    assert "Users can't X." in row["payload_md"]
    # Part B was NOT generated alongside the human PRD.
    assert (row["llm_part"] or "") == ""
    assert (row.get("llm_part_source_hash") or "") == ""


def test_human_prd_carries_html_page_contract(isolated_settings, monkeypatch):
    """Part A (prd-author v4.2) is generated against the HTML PAGE contract — the
    skill's HTML template (with the canonical `<style>` + `contenteditable` page)
    reaches the prompt, and the directive steers to ONE self-contained HTML
    document, no `:::` blocks, no code fence, no Implementation Spec."""
    _seed_corpus(isolated_settings["data_dir"])
    db_mod = isolated_settings["db"]
    brief_id = _seed_brief(db_mod)
    prd_id = _start_prd(db_mod, brief_id)

    call, captured = _part_a_mock()
    monkeypatch.setattr(prd_runner, "llm_call", call)
    prd_runner._run_sync(prd_id, brief_id, 0)

    a_input = captured[0]["input"]
    # The skill's HTML template (markup + design system) reaches the prompt…
    assert "<!DOCTYPE html>" in a_input
    assert 'contenteditable="true"' in a_input
    # …in the v4.1 section order (eyebrows)…
    for label in (">Context", ">Problem", ">Evidence", ">Requirements", ">Appendix"):
        assert label in a_input, f"human PRD prompt missing section {label!r}"
    # …the directive steers to a self-contained HTML page, not markdown / blocks…
    assert "self-contained HTML page" in a_input
    assert ":::" not in a_input, "HTML human PRD must not impose `:::` blocks"
    assert "Start your output at `<!DOCTYPE html>`" in a_input
    # …and _run_sync passes no author → the byline renders the [NEED: author] slot.
    assert prd_runner._AUTHOR_FALLBACK in a_input
    # The system prompt carries the raw-HTML / no-code-fence output contract.
    assert "Markdown code fence" in captured[0]["system"]


def test_run_sync_uses_fallback_title(isolated_settings, monkeypatch):
    _seed_corpus(isolated_settings["data_dir"])
    db_mod = isolated_settings["db"]
    brief_id = _seed_brief(db_mod, insights=[{}])
    prd_id = _start_prd(db_mod, brief_id, title="placeholder")

    call, _ = _part_a_mock()
    monkeypatch.setattr(prd_runner, "llm_call", call)
    prd_runner._run_sync(prd_id, brief_id, 0)
    assert db_mod.get_prd(prd_id)["title"] == "Insight #1"


def test_generate_prd_warms_part_b_in_background(isolated_settings, monkeypatch):
    """The async generate_prd entry point produces the human PRD (Part A), then
    PRE-WARMS the Implementation Spec (Part B) in the background so the Tickets
    tab can inherit acceptance criteria from it — the spec is cached in llm_part
    without ever being surfaced to the user. The synchronous _run_sync path does
    NOT warm (Part B stays strictly on demand there)."""
    _seed_corpus(isolated_settings["data_dir"])
    db_mod = isolated_settings["db"]
    brief_id = _seed_brief(db_mod)
    prd_id = _start_prd(db_mod, brief_id)

    call, captured = _part_a_mock()
    monkeypatch.setattr(prd_runner, "llm_call", call)

    async def _run() -> None:
        await prd_runner.generate_prd(prd_id, brief_id, 0)
        # Drain the fire-and-forget Part B pre-warm task(s) so the assertion sees
        # a settled state rather than racing the background warm.
        pending = list(prd_runner._impl_spec_warm_tasks)
        if pending:
            await asyncio.gather(*pending)

    asyncio.run(_run())

    purposes = [c["purpose"] for c in captured]
    assert "generate_prd_part_a" in purposes  # human PRD generated
    assert "generate_prd_part_b" in purposes  # Implementation Spec pre-warmed
    row = db_mod.get_prd(prd_id)
    assert row["status"] == "ready"
    assert "Users can't X." in row["payload_md"]
    assert (row["llm_part"] or "") != ""  # spec cached in the background


def test_run_sync_part_a_renders_as_before(isolated_settings, monkeypatch):
    """Frontend-compat: payload_md is the human PRD only, no separator artifacts;
    get_prd_rendered returns the same."""
    _seed_corpus(isolated_settings["data_dir"])
    db_mod = isolated_settings["db"]
    brief_id = _seed_brief(db_mod)
    prd_id = _start_prd(db_mod, brief_id)

    call, _ = _part_a_mock()
    monkeypatch.setattr(prd_runner, "llm_call", call)
    prd_runner._run_sync(prd_id, brief_id, 0)

    payload = db_mod.get_prd(prd_id)["payload_md"]
    assert payload.startswith("# Surface")
    assert not payload.rstrip().endswith("---")
    rendered = db_mod.get_prd_rendered(prd_id)
    assert rendered["payload_md"] == payload


# ── on-demand Implementation Spec (Part B) + caching ─────────────────────────

def _ready_human_prd(isolated_settings, monkeypatch, part_a=_PART_A):
    """Generate a ready human PRD and return (db_mod, prd_id)."""
    _seed_corpus(isolated_settings["data_dir"])
    db_mod = isolated_settings["db"]
    brief_id = _seed_brief(db_mod)
    prd_id = _start_prd(db_mod, brief_id)
    call, _ = _part_a_mock(part_a=part_a)
    monkeypatch.setattr(prd_runner, "llm_call", call)
    prd_runner._run_sync(prd_id, brief_id, 0)
    return db_mod, prd_id


def test_ensure_impl_spec_generates_via_implementation_spec_skill(
    isolated_settings, monkeypatch
):
    """First send: Part B is generated by the implementation-spec skill, fed the
    finished human PRD, and stored in llm_part."""
    db_mod, prd_id = _ready_human_prd(isolated_settings, monkeypatch)

    captured: list = []

    def _spec_call(**kwargs):
        captured.append(kwargs)
        return _llm_result(_PART_B, prompt_version="prd-impl-spec-v1")

    monkeypatch.setattr(prd_runner, "llm_call", _spec_call)
    result = prd_runner.ensure_impl_spec(prd_id)

    assert result["cached"] is False
    assert "WHEN x THE SYSTEM SHALL y." in result["llm_part"]
    # Exactly one implementation-spec call, fed the finished human PRD.
    assert len(captured) == 1
    assert captured[0]["skill"] == "implementation-spec"
    assert captured[0]["purpose"] == "generate_prd_part_b"
    assert "PART A — HUMAN PRD" in captured[0]["input"]
    assert "Ship the thing" in captured[0]["input"]  # human PRD text flows in
    # Persisted to llm_part keyed to the human PRD hash.
    row = db_mod.get_prd(prd_id)
    assert "Implementation Spec" in row["llm_part"]
    assert row["llm_part_source_hash"]


def test_ensure_impl_spec_caches_second_send_reuses(isolated_settings, monkeypatch):
    """Second send with an unchanged human PRD reuses the cache — NO second
    implementation-spec call."""
    db_mod, prd_id = _ready_human_prd(isolated_settings, monkeypatch)

    calls = {"n": 0}

    def _spec_call(**kwargs):
        calls["n"] += 1
        return _llm_result(_PART_B, prompt_version="prd-impl-spec-v1")

    monkeypatch.setattr(prd_runner, "llm_call", _spec_call)

    first = prd_runner.ensure_impl_spec(prd_id)
    second = prd_runner.ensure_impl_spec(prd_id)

    assert first["cached"] is False
    assert second["cached"] is True
    assert second["llm_part"] == first["llm_part"]
    # The model was invoked exactly once across both sends.
    assert calls["n"] == 1


def test_editing_human_prd_invalidates_spec_cache(isolated_settings, monkeypatch):
    """Editing the human PRD invalidates the cached spec: the next send
    regenerates (cache miss) against the new text."""
    db_mod, prd_id = _ready_human_prd(isolated_settings, monkeypatch)

    outputs = ["# Spec v1\nWHEN a THE SYSTEM SHALL b.", "# Spec v2\nWHEN c THE SYSTEM SHALL d."]
    idx = {"i": 0}

    def _spec_call(**kwargs):
        out = outputs[idx["i"]]
        idx["i"] += 1
        return _llm_result(out, prompt_version="prd-impl-spec-v1")

    monkeypatch.setattr(prd_runner, "llm_call", _spec_call)

    first = prd_runner.ensure_impl_spec(prd_id)
    assert first["cached"] is False
    assert "Spec v1" in first["llm_part"]

    # Edit the human PRD — this clears llm_part + the source hash.
    from app.db.prds import update_prd_content
    update_prd_content(prd_id, title="t", payload_md="# Edited PRD\nbrand new body")
    row = db_mod.get_prd(prd_id)
    assert (row["llm_part"] or "") == ""
    assert (row.get("llm_part_source_hash") or "") == ""

    # Next send is a cache MISS and regenerates against the edited PRD.
    second = prd_runner.ensure_impl_spec(prd_id)
    assert second["cached"] is False
    assert "Spec v2" in second["llm_part"]
    # The spec call was fed the EDITED human PRD text.
    # (idx advanced twice → two distinct generations.)
    assert idx["i"] == 2


def test_changed_prd_text_alone_forces_regenerate(isolated_settings, monkeypatch):
    """Even without going through update_prd_content, a payload_md whose hash
    differs from the cached source_hash forces a regenerate (hash check is the
    source of truth)."""
    db_mod, prd_id = _ready_human_prd(isolated_settings, monkeypatch)

    monkeypatch.setattr(
        prd_runner, "llm_call",
        lambda **kw: _llm_result(_PART_B, prompt_version="prd-impl-spec-v1"),
    )
    prd_runner.ensure_impl_spec(prd_id)  # populate cache

    # Simulate a stale cache: keep llm_part but mutate payload_md directly.
    db_mod.get_prd(prd_id)
    isolated_settings["supabase"].table("prds").update(
        {"payload_md": "# Totally different PRD body"}
    ).eq("id", prd_id).execute()

    calls = {"n": 0}

    def _spec_call(**kwargs):
        calls["n"] += 1
        return _llm_result("# regenerated", prompt_version="prd-impl-spec-v1")

    monkeypatch.setattr(prd_runner, "llm_call", _spec_call)
    result = prd_runner.ensure_impl_spec(prd_id)
    assert result["cached"] is False
    assert calls["n"] == 1


def test_ensure_impl_spec_missing_prd_raises(isolated_settings):
    with pytest.raises(RuntimeError):
        prd_runner.ensure_impl_spec(99999)


def test_ensure_impl_spec_empty_human_prd_raises(isolated_settings, monkeypatch):
    """A PRD row with no human body has nothing to build a spec from."""
    db_mod = isolated_settings["db"]
    brief_id = _seed_brief(db_mod)
    prd_id = _start_prd(db_mod, brief_id)  # payload_md == '' (never completed)
    with pytest.raises(RuntimeError):
        prd_runner.ensure_impl_spec(prd_id)


def test_ensure_impl_spec_decision_logged(isolated_settings, monkeypatch):
    """The on-demand spec generation is decision-logged (generate_impl_spec)."""
    db_mod, prd_id = _ready_human_prd(isolated_settings, monkeypatch)
    monkeypatch.setattr(prd_runner, "company_id_for_slug", lambda _slug: "co-test")
    monkeypatch.setattr(
        prd_runner, "llm_call",
        lambda **kw: _llm_result(_PART_B, prompt_version="prd-impl-spec-v1"),
    )
    prd_runner.ensure_impl_spec(prd_id)

    sup = isolated_settings["supabase"]
    rows = sup.table("agent_decision_log").select("*").execute().data
    spec = [r for r in rows if r["decision_type"] == "generate_impl_spec"]
    assert len(spec) == 1
    assert spec[0]["factors"]["skill"] == "implementation-spec"
    assert spec[0]["factors"]["has_llm_part"] is True


# ── real-gateway: each flow carries its skill's METHOD ───────────────────────

def test_real_gateway_human_prd_carries_prd_author_method(isolated_settings, monkeypatch):
    """The human-PRD flow's prompt carries the prd-author METHOD (and not the
    implementation-spec METHOD)."""
    _seed_corpus(isolated_settings["data_dir"])
    db_mod = isolated_settings["db"]
    brief_id = _seed_brief(db_mod)
    prd_id = _start_prd(db_mod, brief_id)

    systems: dict[str, str] = {}

    def _call_md(**kwargs):
        systems["a"] = kwargs["system"]
        return _PART_A

    import app.graph.gateway as gw
    monkeypatch.setattr(gw, "call_md", _call_md)
    prd_runner._run_sync(prd_id, brief_id, 0)

    assert "METHOD (skill: prd-author" in systems["a"]
    assert "Sprntly's PRD Page generator" in systems["a"]
    # The human-PRD flow must NOT carry the implementation-spec METHOD.
    assert "METHOD (skill: implementation-spec" not in systems["a"]


def test_real_gateway_spec_carries_implementation_spec_method(
    isolated_settings, monkeypatch
):
    """The on-demand spec flow's prompt carries the implementation-spec METHOD
    and is fed the finished human PRD."""
    # Seed a ready human PRD directly (no llm_call patch) so the on-demand spec
    # path drives the REAL gateway through call_md.
    _seed_corpus(isolated_settings["data_dir"])
    db_mod = isolated_settings["db"]
    brief_id = _seed_brief(db_mod)
    prd_id = _start_prd(db_mod, brief_id)
    db_mod.complete_prd(prd_id, title="t", md=_PART_A)

    systems: dict[str, str] = {}

    def _call_md(**kwargs):
        systems["b"] = kwargs["system"]
        assert "PART A — HUMAN PRD" in kwargs["user"]
        return _PART_B

    import app.graph.gateway as gw
    monkeypatch.setattr(gw, "call_md", _call_md)
    result = prd_runner.ensure_impl_spec(prd_id)

    assert "METHOD (skill: implementation-spec" in systems["b"]
    assert "Sprntly's Implementation Spec agent" in systems["b"]
    assert "Implementation Spec" in result["llm_part"]


# ── error paths (human-PRD flow) ─────────────────────────────────────────────

def test_run_sync_missing_brief_raises(isolated_settings):
    with pytest.raises(RuntimeError):
        prd_runner._run_sync(1, brief_id=9999, insight_index=0)


def test_run_sync_out_of_range_insight_raises(isolated_settings):
    db_mod = isolated_settings["db"]
    brief_id = _seed_brief(db_mod, insights=[{"title": "only-one"}])
    with pytest.raises(RuntimeError):
        prd_runner._run_sync(1, brief_id=brief_id, insight_index=5)


def test_generate_prd_records_failure_in_db(isolated_settings, monkeypatch):
    _seed_corpus(isolated_settings["data_dir"])
    db_mod = isolated_settings["db"]
    brief_id = _seed_brief(db_mod)
    prd_id = _start_prd(db_mod, brief_id)

    def _boom(**_kw):
        raise ValueError("LLM exploded")

    monkeypatch.setattr(prd_runner, "llm_call", _boom)
    asyncio.run(prd_runner.generate_prd(prd_id, brief_id, 0))

    row = db_mod.get_prd(prd_id)
    assert row["status"] == "failed"
    assert "ValueError" in (row["error"] or "")


# ── format/style exemplars (company gold-standard templates) ─────────────────

def _wire_templates(isolated_settings, monkeypatch, company_id="co-tpl"):
    """Point company_template storage at the fake db, seed a company, and make
    the runner resolve the brief's slug to that company."""
    db = isolated_settings["supabase"]
    if not db.table("companies").select("id").eq("id", company_id).execute().data:
        db.table("companies").insert(
            {"id": company_id, "slug": "asurion", "display_name": "Co"}
        ).execute()
    import app.company_template as ct
    monkeypatch.setattr(ct, "require_client", lambda: db)
    monkeypatch.setattr(prd_runner, "company_id_for_slug", lambda _slug: company_id)
    return ct


def test_templates_reach_human_prd_call(isolated_settings, monkeypatch):
    """A company's uploaded gold-standard templates are folded into the human-PRD
    call as a FORMAT/STYLE EXEMPLARS block so the PRD matches house style."""
    _seed_corpus(isolated_settings["data_dir"])
    db_mod = isolated_settings["db"]
    brief_id = _seed_brief(db_mod)
    prd_id = _start_prd(db_mod, brief_id)

    ct = _wire_templates(isolated_settings, monkeypatch)
    ct.save_company_template(
        "co-tpl", filename="gold.md", data=b"GOLD_TEMPLATE_MARK", label="House style"
    )

    call, captured = _part_a_mock()
    monkeypatch.setattr(prd_runner, "llm_call", call)
    prd_runner._run_sync(prd_id, brief_id, 0)

    assert len(captured) == 1
    assert "FORMAT/STYLE EXEMPLARS" in captured[0]["input"]
    assert "GOLD_TEMPLATE_MARK" in captured[0]["input"]
    assert "House style" in captured[0]["input"]


def test_no_templates_is_clean_no_op(isolated_settings, monkeypatch):
    """No templates uploaded ⇒ no exemplars block in the human-PRD call."""
    _seed_corpus(isolated_settings["data_dir"])
    db_mod = isolated_settings["db"]
    brief_id = _seed_brief(db_mod)
    prd_id = _start_prd(db_mod, brief_id)

    _wire_templates(isolated_settings, monkeypatch)  # company exists, but no templates

    call, captured = _part_a_mock()
    monkeypatch.setattr(prd_runner, "llm_call", call)
    prd_runner._run_sync(prd_id, brief_id, 0)

    assert "FORMAT/STYLE EXEMPLARS" not in captured[0]["input"]
    assert db_mod.get_prd(prd_id)["status"] == "ready"


def test_template_lookup_failure_does_not_break_prd(isolated_settings, monkeypatch):
    """A templates read error degrades to no exemplars — never fails the PRD."""
    _seed_corpus(isolated_settings["data_dir"])
    db_mod = isolated_settings["db"]
    brief_id = _seed_brief(db_mod)
    prd_id = _start_prd(db_mod, brief_id)

    monkeypatch.setattr(prd_runner, "company_id_for_slug", lambda _slug: "co-x")

    def _boom(*_a, **_k):
        raise RuntimeError("templates backend down")

    monkeypatch.setattr(prd_runner, "render_templates_for_prompt", _boom)

    call, captured = _part_a_mock()
    monkeypatch.setattr(prd_runner, "llm_call", call)
    prd_runner._run_sync(prd_id, brief_id, 0)

    assert db_mod.get_prd(prd_id)["status"] == "ready"
    assert "FORMAT/STYLE EXEMPLARS" not in captured[0]["input"]


# ── byline: account owner is the author when no logged-in author is supplied ──

def _seed_owner(sb, *, slug="asurion", company_id="co-asurion",
                user_id="u-owner", full_name="Dana Owner", role="owner"):
    """Seed a company owned by `full_name` so company_id_for_slug(slug) resolves
    and owner_name_for_company(company_id) returns the owner's name."""
    sb.table("companies").insert(
        {"id": company_id, "slug": slug, "display_name": slug.title()}
    ).execute()
    sb.table("company_members").insert(
        {"id": f"cm-{company_id}-{user_id}", "company_id": company_id,
         "user_id": user_id, "role": role}
    ).execute()
    sb.table("profiles").insert({"id": user_id, "full_name": full_name}).execute()
    return company_id


def test_byline_falls_back_to_account_owner_when_no_author(isolated_settings, monkeypatch):
    """A background/brief-generated PRD (author=None) puts the ACCOUNT OWNER's
    name on the byline instead of the `[NEED: author]` placeholder."""
    _seed_corpus(isolated_settings["data_dir"])
    db_mod = isolated_settings["db"]
    _seed_owner(isolated_settings["supabase"])  # "asurion" owned by Dana Owner
    brief_id = _seed_brief(db_mod)              # dataset defaults to "asurion"
    prd_id = _start_prd(db_mod, brief_id)

    call, captured = _part_a_mock()
    monkeypatch.setattr(prd_runner, "llm_call", call)
    prd_runner._run_sync(prd_id, brief_id, 0)   # sync path passes author=None

    # The byline slot (backtick-wrapped) carries the owner's name, not the
    # placeholder. (The HTML template mentions "[NEED: author]" as instruction
    # text, so assert on the backtick-wrapped byline to disambiguate.)
    directive = captured[0]["input"]
    assert "`Dana Owner`" in directive
    assert "`[NEED: author]`" not in directive


def test_explicit_author_overrides_the_owner_fallback(isolated_settings, monkeypatch):
    """A logged-in user's name (passed by the /v1/prd/generate route) still wins
    over the owner fallback."""
    _seed_corpus(isolated_settings["data_dir"])
    db_mod = isolated_settings["db"]
    _seed_owner(isolated_settings["supabase"])
    brief_id = _seed_brief(db_mod)
    prd_id = _start_prd(db_mod, brief_id)

    call, captured = _part_a_mock()
    monkeypatch.setattr(prd_runner, "llm_call", call)
    asyncio.run(prd_runner.generate_prd(prd_id, brief_id, 0, author="Logged In User"))

    directive = captured[0]["input"]
    assert "`Logged In User`" in directive
    assert "Dana Owner" not in directive


def test_byline_needs_author_when_no_owner_resolves(isolated_settings, monkeypatch):
    """No company/owner on file → the byline keeps the `[NEED: author]`
    placeholder (unchanged behaviour for ownerless/legacy datasets)."""
    _seed_corpus(isolated_settings["data_dir"])
    db_mod = isolated_settings["db"]
    brief_id = _seed_brief(db_mod)              # no company seeded for "asurion"
    prd_id = _start_prd(db_mod, brief_id)

    call, captured = _part_a_mock()
    monkeypatch.setattr(prd_runner, "llm_call", call)
    prd_runner._run_sync(prd_id, brief_id, 0)

    # The byline slot itself (backtick-wrapped) keeps the placeholder.
    assert "`[NEED: author]`" in captured[0]["input"]


def test_owner_name_for_company_prefers_owner_then_admin(isolated_settings):
    """The lookup returns the owner's name; falls back to an admin's; None for an
    unknown company."""
    from app.db.companies import owner_name_for_company

    sb = isolated_settings["supabase"]
    _seed_owner(sb, slug="acme", company_id="co-acme", user_id="u-o",
                full_name="Olivia Owner", role="owner")
    # An admin on the same company must NOT shadow the owner.
    sb.table("company_members").insert(
        {"id": "cm-co-acme-u-a", "company_id": "co-acme", "user_id": "u-a", "role": "admin"}
    ).execute()
    sb.table("profiles").insert({"id": "u-a", "full_name": "Adam Admin"}).execute()
    assert owner_name_for_company("co-acme") == "Olivia Owner"

    # Admin-only company → the admin is used.
    sb.table("companies").insert({"id": "co-noown", "slug": "noown", "display_name": "Noown"}).execute()
    sb.table("company_members").insert(
        {"id": "cm-co-noown-u-b", "company_id": "co-noown", "user_id": "u-b", "role": "admin"}
    ).execute()
    sb.table("profiles").insert({"id": "u-b", "first_name": "Amy", "last_name": "Admin"}).execute()
    assert owner_name_for_company("co-noown") == "Amy Admin"

    assert owner_name_for_company("co-missing") is None
    assert owner_name_for_company(None) is None


# ── Evidence header carries NO "View evidence page" link ──────────────────────

def test_prd_template_has_no_evidence_link():
    """The skill's HTML template renders the Evidence header as a plain label —
    no `View evidence page` link, no evidence href, no leftover `.evhead` CSS."""
    tpl = prd_runner._load_part_a_template()
    assert "View evidence page" not in tpl
    assert "app.sprntly.ai/evidence" not in tpl
    assert "evhead" not in tpl
    assert '<div class="eyebrow">Evidence</div>' in tpl


def test_part_a_directive_has_no_evidence_link_placeholder():
    """The directive no longer injects an evidence-page URL and instructs the
    model to leave the Evidence header link-free."""
    d = prd_runner._PART_A_DIRECTIVE
    assert "{evidence_page}" not in d
    assert "View evidence page" not in d
    assert "NO link" in d


def test_generated_prompt_carries_no_evidence_link(isolated_settings, monkeypatch):
    """End-to-end: the prompt sent to the model (directive + REAL template)
    contains no `View evidence page` link and no evidence URL."""
    _seed_corpus(isolated_settings["data_dir"])
    db_mod = isolated_settings["db"]
    brief_id = _seed_brief(db_mod)
    prd_id = _start_prd(db_mod, brief_id)

    call, captured = _part_a_mock()
    monkeypatch.setattr(prd_runner, "llm_call", call)
    prd_runner._run_sync(prd_id, brief_id, 0)

    prompt = captured[0]["input"]
    assert "View evidence page" not in prompt
    assert "app.sprntly.ai/evidence" not in prompt
    # The Evidence section itself is still present (just link-free).
    assert "Evidence" in prompt
