"""Tests for app.prd_runner — the SPLIT PRD generation.

The human PRD (Part A) and the machine-readable Implementation Spec (Part B) are
now generated by two SEPARATE flows:

  - `generate_prd` / `_run_sync` generate ONLY the human PRD via the `prd-author`
    skill and store it in payload_md. They do NOT produce or trigger Part B.
  - `ensure_impl_spec` generates Part B ON DEMAND via the `implementation-spec`
    skill (fed the finished human PRD), caches it in `llm_part` keyed to the
    human PRD's content hash, and is idempotent: a re-send reuses the cache;
    editing the human PRD invalidates it so the next send regenerates.

These tests mock at the gateway/llm seam: most patch `prd_runner.llm_call`; a
couple let the REAL gateway run and patch `app.llm.call_md` to assert the
METHOD (prd-author for the PRD, implementation-spec for the spec) reaches the
prompt.

New rows are written with variant='v2' by the route; the runner itself
produces the human PRD and calls `complete_prd` against the existing row.
"""
from __future__ import annotations

import asyncio

import pytest

from app import prd_runner
from app.graph.gateway import LLMResult


def _seed_corpus(data_dir, dataset="asurion", body="corpus body"):
    ds = data_dir / dataset
    ds.mkdir(exist_ok=True)
    (ds / "a.md").write_text(body)


def _seed_brief(db_mod, dataset="asurion", insights=None):
    if insights is None:
        insights = [{"title": "Insight A", "subtitle": "behaviour"}]
    payload = {
        "summary_headline": "stub",
        "insights": insights,
        "_schema_version": 1,
    }
    return db_mod.save_brief(
        dataset=dataset, week_label="Week of stub", payload=payload, schema_version=1
    )


def _llm_result(output, model="claude-sonnet-4-6", prompt_version="prd-author-v2"):
    return LLMResult(
        output=output, model=model, prompt_version=prompt_version,
        input_tokens=10, output_tokens=5, cache_read_input_tokens=0,
        cache_creation_input_tokens=0, cost_usd=0.001, latency_ms=5,
        stop_reason="end_turn",
    )


_PART_A = (
    "# Surface — Ship the thing\n\n"
    "# Part A — Product Requirements Document (human-readable)\n"
    "## 1. Problem & evidence\nUsers can't X.\n"
)
_PART_B = (
    "# Implementation Spec\n"
    "## B0. Available artifacts\nWHEN x THE SYSTEM SHALL y.\n"
)


def _part_a_mock(part_a=_PART_A, captured=None):
    """A `llm_call` stub that records each call's kwargs and returns Part A.

    Records the call so a test can assert the human-PRD flow makes exactly ONE
    call and NEVER a Part-B (implementation-spec) call.
    """
    captured = [] if captured is None else captured

    def _call(**kwargs):
        captured.append(kwargs)
        return _llm_result(part_a)

    return _call, captured


def _start_prd(db_mod, brief_id, title="t", insight_index=0):
    return db_mod.start_prd(
        brief_id=brief_id, insight_index=insight_index, title=title,
        template_version=1, variant="v2",
    )


# ── human PRD: Part A only, never triggers Part B ────────────────────────────

def test_run_sync_makes_one_llm_call_for_human_prd(isolated_settings, monkeypatch):
    """The human-PRD flow issues exactly ONE gateway call — the prd-author call.
    It must NOT also issue an implementation-spec (Part B) call."""
    _seed_corpus(isolated_settings["data_dir"])
    db_mod = isolated_settings["db"]
    brief_id = _seed_brief(db_mod)
    prd_id = _start_prd(db_mod, brief_id)

    call, captured = _part_a_mock()
    monkeypatch.setattr(prd_runner, "llm_call", call)
    prd_runner._run_sync(prd_id, brief_id, 0)

    assert len(captured) == 1
    assert captured[0]["purpose"] == "generate_prd_part_a"
    assert captured[0]["skill"] == "prd-author"
    # No implementation-spec call was made.
    assert all(c["skill"] != "implementation-spec" for c in captured)


def test_run_sync_stores_only_human_prd_no_llm_part(isolated_settings, monkeypatch):
    """Part A → payload_md; llm_part stays empty (Part B is on demand, not now)."""
    _seed_corpus(isolated_settings["data_dir"])
    db_mod = isolated_settings["db"]
    brief_id = _seed_brief(db_mod)
    prd_id = _start_prd(db_mod, brief_id)

    call, _ = _part_a_mock()
    monkeypatch.setattr(prd_runner, "llm_call", call)
    prd_runner._run_sync(prd_id, brief_id, 0)

    row = db_mod.get_prd(prd_id)
    assert row["status"] == "ready"
    assert "Part A — Product Requirements Document" in row["payload_md"]
    assert "Users can't X." in row["payload_md"]
    # Part B was NOT generated alongside the human PRD.
    assert (row["llm_part"] or "") == ""
    assert (row.get("llm_part_source_hash") or "") == ""


def test_human_prd_carries_html_page_contract(isolated_settings, monkeypatch):
    """Part A (prd-author v4.2) is generated against the HTML PAGE contract — the
    skill's HTML template (with the canonical `<style>` + `contenteditable` page)
    reaches the prompt, and the directive steers to ONE self-contained HTML
    document, no `:::` blocks, no code fence, no Implementation Spec."""
    _seed_corpus(isolated_settings["data_dir"])
    db_mod = isolated_settings["db"]
    brief_id = _seed_brief(db_mod)
    prd_id = _start_prd(db_mod, brief_id)

    call, captured = _part_a_mock()
    monkeypatch.setattr(prd_runner, "llm_call", call)
    prd_runner._run_sync(prd_id, brief_id, 0)

    a_input = captured[0]["input"]
    # The stable HTML template (markup + design system) now rides the CACHEABLE
    # PREFIX (identical across every PRD → a cache read), not the per-PRD tail.
    a_prefix = captured[0]["user_cacheable_prefix"]
    assert "<!DOCTYPE html>" in a_prefix
    assert 'contenteditable="true"' in a_prefix
    # …in the v4.1 section order (eyebrows)…
    for label in (">Context", ">Problem", ">Evidence", ">Requirements", ">Appendix"):
        assert label in a_prefix, f"human PRD template missing section {label!r}"
    # …the directive (the dynamic tail) steers to an HTML page whose <style> the
    # model leaves EMPTY (the server injects the canonical stylesheet)…
    assert "HTML page" in a_input
    assert "EMPTY" in a_input and "<style>" in a_input
    assert ":::" not in a_input, "HTML human PRD must not impose `:::` blocks"
    assert ":::" not in a_prefix
    assert "Start your output at `<!DOCTYPE html>`" in a_input
    # …and _run_sync passes no author → the byline renders the [NEED: author] slot.
    assert prd_runner._AUTHOR_FALLBACK in a_input
    # The system prompt carries the raw-HTML / no-code-fence output contract.
    assert "Markdown code fence" in captured[0]["system"]


def test_run_sync_uses_fallback_title(isolated_settings, monkeypatch):
    _seed_corpus(isolated_settings["data_dir"])
    db_mod = isolated_settings["db"]
    brief_id = _seed_brief(db_mod, insights=[{}])
    prd_id = _start_prd(db_mod, brief_id, title="placeholder")

    call, _ = _part_a_mock()
    monkeypatch.setattr(prd_runner, "llm_call", call)
    prd_runner._run_sync(prd_id, brief_id, 0)
    assert db_mod.get_prd(prd_id)["title"] == "Insight #1"


def test_generate_prd_async_makes_one_call_no_part_b(isolated_settings, monkeypatch):
    """The async generate_prd entry point produces ONLY the human PRD (one call),
    completing ready with an empty llm_part — the spec is on demand. Pre-warming
    Part B is layered on top by generate_prd_and_warm (below), NOT baked into
    generate_prd, so this and the sync path stay strictly human-PRD-only."""
    _seed_corpus(isolated_settings["data_dir"])
    db_mod = isolated_settings["db"]
    brief_id = _seed_brief(db_mod)
    prd_id = _start_prd(db_mod, brief_id)

    call, captured = _part_a_mock()
    monkeypatch.setattr(prd_runner, "llm_call", call)
    asyncio.run(prd_runner.generate_prd(prd_id, brief_id, 0))

    assert len(captured) == 1
    assert captured[0]["purpose"] == "generate_prd_part_a"
    row = db_mod.get_prd(prd_id)
    assert row["status"] == "ready"
    assert "Users can't X." in row["payload_md"]
    assert (row["llm_part"] or "") == ""


def test_generate_prd_and_warm_pre_warms_part_b(isolated_settings, monkeypatch):
    """generate_prd_and_warm (the interactive/ideation entry point) generates the
    human PRD, then pre-warms the Implementation Spec (Part B) so tickets inherit
    AC — the spec is cached in llm_part without ever being shown to the user."""
    _seed_corpus(isolated_settings["data_dir"])
    db_mod = isolated_settings["db"]
    brief_id = _seed_brief(db_mod)
    prd_id = _start_prd(db_mod, brief_id)

    call, captured = _part_a_mock()
    monkeypatch.setattr(prd_runner, "llm_call", call)
    asyncio.run(prd_runner.generate_prd_and_warm(prd_id, brief_id, 0))

    purposes = [c["purpose"] for c in captured]
    assert "generate_prd_part_a" in purposes  # human PRD generated
    assert "generate_prd_part_b" in purposes  # Implementation Spec pre-warmed
    row = db_mod.get_prd(prd_id)
    assert row["status"] == "ready"
    assert "Users can't X." in row["payload_md"]
    assert (row["llm_part"] or "") != ""  # spec cached in the background


def test_generate_prd_and_warm_pings_requester_on_success(isolated_settings, monkeypatch):
    """When the requester's identity is known, a successful generation fires the
    best-effort Slack "your PRD is ready" ping with the PRD title."""
    _seed_corpus(isolated_settings["data_dir"])
    db_mod = isolated_settings["db"]
    brief_id = _seed_brief(db_mod)
    prd_id = _start_prd(db_mod, brief_id)

    call, _ = _part_a_mock()
    monkeypatch.setattr(prd_runner, "llm_call", call)

    pings: list = []

    async def _fake_notify(company_id, user_id, pid, title):
        pings.append((company_id, user_id, pid, title))

    monkeypatch.setattr(prd_runner, "_notify_prd_ready_slack", _fake_notify)

    asyncio.run(prd_runner.generate_prd_and_warm(
        prd_id, brief_id, 0,
        company_id="ent-A", user_id="user-1", prd_title="Checkout redesign",
    ))
    assert pings == [("ent-A", "user-1", prd_id, "Checkout redesign")]


def test_generate_prd_and_warm_skips_ping_without_identity(isolated_settings, monkeypatch):
    """No company_id/user_id (legacy/test callers) → no Slack ping attempted."""
    _seed_corpus(isolated_settings["data_dir"])
    db_mod = isolated_settings["db"]
    brief_id = _seed_brief(db_mod)
    prd_id = _start_prd(db_mod, brief_id)

    call, _ = _part_a_mock()
    monkeypatch.setattr(prd_runner, "llm_call", call)

    called: list = []

    async def _fake_notify(*a, **k):
        called.append(a)

    monkeypatch.setattr(prd_runner, "_notify_prd_ready_slack", _fake_notify)

    asyncio.run(prd_runner.generate_prd_and_warm(prd_id, brief_id, 0))
    assert called == []


def test_generate_prd_and_warm_streams_part_a_over_channel(isolated_settings, monkeypatch):
    """Part A deltas are published to the prd:<id> channel as the HTML streams,
    then a terminal 'done' — the SSE route relays these to the client."""
    from app.graph import token_stream

    _seed_corpus(isolated_settings["data_dir"])
    db_mod = isolated_settings["db"]
    brief_id = _seed_brief(db_mod)
    prd_id = _start_prd(db_mod, brief_id)

    async def _flow():
        chan = f"prd:{prd_id}"
        collected: list[dict] = []

        async def _sub():
            async for f in token_stream.subscribe(chan):
                collected.append(f)

        sub_task = asyncio.ensure_future(_sub())
        await asyncio.sleep(0)  # let the subscriber register its queue

        def _call(**kwargs):
            od = kwargs.get("on_delta")
            if kwargs.get("purpose") == "generate_prd_part_a" and od:
                od("<h1>Streaming")
                od(" PRD</h1>")
            return _llm_result(_PART_A)

        monkeypatch.setattr(prd_runner, "llm_call", _call)
        await prd_runner.generate_prd_and_warm(prd_id, brief_id, 0)
        await asyncio.sleep(0)  # flush the scheduled publishes + terminal close
        await sub_task
        return collected

    frames = asyncio.run(_flow())
    deltas = [f["text"] for f in frames if f["kind"] == "delta"]
    assert "".join(deltas) == "<h1>Streaming PRD</h1>"
    assert frames[-1]["kind"] == "done", "terminal frame closes the stream"


def test_run_sync_part_a_renders_as_before(isolated_settings, monkeypatch):
    """Frontend-compat: payload_md is the human PRD only, no separator artifacts;
    get_prd_rendered returns the same."""
    _seed_corpus(isolated_settings["data_dir"])
    db_mod = isolated_settings["db"]
    brief_id = _seed_brief(db_mod)
    prd_id = _start_prd(db_mod, brief_id)

    call, _ = _part_a_mock()
    monkeypatch.setattr(prd_runner, "llm_call", call)
    prd_runner._run_sync(prd_id, brief_id, 0)

    payload = db_mod.get_prd(prd_id)["payload_md"]
    # The human PRD body is preserved; the canonical stylesheet is injected
    # server-side at finalize (Phase 2), so the stored doc is self-contained.
    assert "# Surface — Ship the thing" in payload
    assert ":root{--green:#1A6B47" in payload
    assert not payload.rstrip().endswith("---")
    rendered = db_mod.get_prd_rendered(prd_id)
    assert rendered["payload_md"] == payload


# ── on-demand Implementation Spec (Part B) + caching ─────────────────────────

def _ready_human_prd(isolated_settings, monkeypatch, part_a=_PART_A):
    """Generate a ready human PRD and return (db_mod, prd_id)."""
    _seed_corpus(isolated_settings["data_dir"])
    db_mod = isolated_settings["db"]
    brief_id = _seed_brief(db_mod)
    prd_id = _start_prd(db_mod, brief_id)
    call, _ = _part_a_mock(part_a=part_a)
    monkeypatch.setattr(prd_runner, "llm_call", call)
    prd_runner._run_sync(prd_id, brief_id, 0)
    return db_mod, prd_id


def test_ensure_impl_spec_generates_via_implementation_spec_skill(
    isolated_settings, monkeypatch
):
    """First send: Part B is generated by the implementation-spec skill, fed the
    finished human PRD, and stored in llm_part."""
    db_mod, prd_id = _ready_human_prd(isolated_settings, monkeypatch)

    captured: list = []

    def _spec_call(**kwargs):
        captured.append(kwargs)
        return _llm_result(_PART_B, prompt_version="prd-impl-spec-v1")

    monkeypatch.setattr(prd_runner, "llm_call", _spec_call)
    result = prd_runner.ensure_impl_spec(prd_id)

    assert result["cached"] is False
    assert "WHEN x THE SYSTEM SHALL y." in result["llm_part"]
    # Exactly one implementation-spec call, fed the finished human PRD.
    assert len(captured) == 1
    assert captured[0]["skill"] == "implementation-spec"
    assert captured[0]["purpose"] == "generate_prd_part_b"
    assert "PART A — HUMAN PRD" in captured[0]["input"]
    assert "Ship the thing" in captured[0]["input"]  # human PRD text flows in
    # Persisted to llm_part keyed to the human PRD hash.
    row = db_mod.get_prd(prd_id)
    assert "Implementation Spec" in row["llm_part"]
    assert row["llm_part_source_hash"]


def test_ensure_impl_spec_caches_second_send_reuses(isolated_settings, monkeypatch):
    """Second send with an unchanged human PRD reuses the cache — NO second
    implementation-spec call."""
    db_mod, prd_id = _ready_human_prd(isolated_settings, monkeypatch)

    calls = {"n": 0}

    def _spec_call(**kwargs):
        calls["n"] += 1
        return _llm_result(_PART_B, prompt_version="prd-impl-spec-v1")

    monkeypatch.setattr(prd_runner, "llm_call", _spec_call)

    first = prd_runner.ensure_impl_spec(prd_id)
    second = prd_runner.ensure_impl_spec(prd_id)

    assert first["cached"] is False
    assert second["cached"] is True
    assert second["llm_part"] == first["llm_part"]
    # The model was invoked exactly once across both sends.
    assert calls["n"] == 1


def test_ensure_impl_spec_single_flight_concurrent_miss(
    isolated_settings, monkeypatch
):
    """Two concurrent cache-miss callers (the post-Part-A warm racing the ticket
    route's warm-on-generate) collapse to ONE Part B generation: the loser waits
    on the per-PRD lock, re-reads the cache, and returns the winner's spec."""
    import threading
    import time as _time

    db_mod, prd_id = _ready_human_prd(isolated_settings, monkeypatch)

    calls = {"n": 0}
    entered = threading.Event()

    def _slow_spec_call(**kwargs):
        calls["n"] += 1
        entered.set()
        _time.sleep(0.2)  # hold the generation long enough for the race to form
        return _llm_result(_PART_B, prompt_version="prd-impl-spec-v1")

    monkeypatch.setattr(prd_runner, "llm_call", _slow_spec_call)

    results: list[dict] = []
    errors: list[Exception] = []

    def _caller():
        try:
            results.append(prd_runner.ensure_impl_spec(prd_id))
        except Exception as exc:  # noqa: BLE001 — surfaced via the errors list
            errors.append(exc)

    t1 = threading.Thread(target=_caller)
    t2 = threading.Thread(target=_caller)
    t1.start()
    entered.wait(timeout=2)  # ensure t1 is mid-generation before t2 races it
    t2.start()
    t1.join(timeout=5)
    t2.join(timeout=5)

    assert not errors
    assert calls["n"] == 1, "concurrent misses must collapse to one generation"
    assert len(results) == 2
    assert results[0]["llm_part"] == results[1]["llm_part"]
    # One of the two saw the winner's cache; flags are one False, one True.
    assert sorted(r["cached"] for r in results) == [False, True]


def test_editing_human_prd_invalidates_spec_cache(isolated_settings, monkeypatch):
    """Editing the human PRD invalidates the cached spec: the next send
    regenerates (cache miss) against the new text."""
    db_mod, prd_id = _ready_human_prd(isolated_settings, monkeypatch)

    outputs = ["# Spec v1\nWHEN a THE SYSTEM SHALL b.", "# Spec v2\nWHEN c THE SYSTEM SHALL d."]
    idx = {"i": 0}

    def _spec_call(**kwargs):
        out = outputs[idx["i"]]
        idx["i"] += 1
        return _llm_result(out, prompt_version="prd-impl-spec-v1")

    monkeypatch.setattr(prd_runner, "llm_call", _spec_call)

    first = prd_runner.ensure_impl_spec(prd_id)
    assert first["cached"] is False
    assert "Spec v1" in first["llm_part"]

    # Edit the human PRD — this clears llm_part + the source hash.
    from app.db.prds import update_prd_content
    update_prd_content(prd_id, title="t", payload_md="# Edited PRD\nbrand new body")
    row = db_mod.get_prd(prd_id)
    assert (row["llm_part"] or "") == ""
    assert (row.get("llm_part_source_hash") or "") == ""

    # Next send is a cache MISS and regenerates against the edited PRD.
    second = prd_runner.ensure_impl_spec(prd_id)
    assert second["cached"] is False
    assert "Spec v2" in second["llm_part"]
    # The spec call was fed the EDITED human PRD text.
    # (idx advanced twice → two distinct generations.)
    assert idx["i"] == 2


def test_changed_prd_text_alone_forces_regenerate(isolated_settings, monkeypatch):
    """Even without going through update_prd_content, a payload_md whose hash
    differs from the cached source_hash forces a regenerate (hash check is the
    source of truth)."""
    db_mod, prd_id = _ready_human_prd(isolated_settings, monkeypatch)

    monkeypatch.setattr(
        prd_runner, "llm_call",
        lambda **kw: _llm_result(_PART_B, prompt_version="prd-impl-spec-v1"),
    )
    prd_runner.ensure_impl_spec(prd_id)  # populate cache

    # Simulate a stale cache: keep llm_part but mutate payload_md directly.
    db_mod.get_prd(prd_id)
    isolated_settings["supabase"].table("prds").update(
        {"payload_md": "# Totally different PRD body"}
    ).eq("id", prd_id).execute()

    calls = {"n": 0}

    def _spec_call(**kwargs):
        calls["n"] += 1
        return _llm_result("# regenerated", prompt_version="prd-impl-spec-v1")

    monkeypatch.setattr(prd_runner, "llm_call", _spec_call)
    result = prd_runner.ensure_impl_spec(prd_id)
    assert result["cached"] is False
    assert calls["n"] == 1


def test_ensure_impl_spec_missing_prd_raises(isolated_settings):
    with pytest.raises(RuntimeError):
        prd_runner.ensure_impl_spec(99999)


def test_ensure_impl_spec_empty_human_prd_raises(isolated_settings, monkeypatch):
    """A PRD row with no human body has nothing to build a spec from."""
    db_mod = isolated_settings["db"]
    brief_id = _seed_brief(db_mod)
    prd_id = _start_prd(db_mod, brief_id)  # payload_md == '' (never completed)
    with pytest.raises(RuntimeError):
        prd_runner.ensure_impl_spec(prd_id)


def test_ensure_impl_spec_decision_logged(isolated_settings, monkeypatch):
    """The on-demand spec generation is decision-logged (generate_impl_spec)."""
    db_mod, prd_id = _ready_human_prd(isolated_settings, monkeypatch)
    monkeypatch.setattr(prd_runner, "company_id_for_slug", lambda _slug: "co-test")
    monkeypatch.setattr(
        prd_runner, "llm_call",
        lambda **kw: _llm_result(_PART_B, prompt_version="prd-impl-spec-v1"),
    )
    prd_runner.ensure_impl_spec(prd_id)

    sup = isolated_settings["supabase"]
    rows = sup.table("agent_decision_log").select("*").execute().data
    spec = [r for r in rows if r["decision_type"] == "generate_impl_spec"]
    assert len(spec) == 1
    assert spec[0]["factors"]["skill"] == "implementation-spec"
    assert spec[0]["factors"]["has_llm_part"] is True


# ── real-gateway: each flow carries its skill's METHOD ───────────────────────

def test_real_gateway_human_prd_carries_prd_author_method(isolated_settings, monkeypatch):
    """The human-PRD flow's prompt carries the prd-author METHOD (and not the
    implementation-spec METHOD)."""
    _seed_corpus(isolated_settings["data_dir"])
    db_mod = isolated_settings["db"]
    brief_id = _seed_brief(db_mod)
    prd_id = _start_prd(db_mod, brief_id)

    systems: dict[str, str] = {}
    prefixes: dict[str, str] = {}

    def _call_md(**kwargs):
        systems["a"] = kwargs["system"]
        prefixes["a"] = kwargs.get("user_cacheable_prefix") or ""
        return _PART_A

    import app.graph.gateway as gw
    monkeypatch.setattr(gw, "call_md", _call_md)
    prd_runner._run_sync(prd_id, brief_id, 0)

    # The skill METHOD now rides the cacheable prefix (not the system prompt).
    assert "METHOD (skill: prd-author" in prefixes["a"]
    assert "Sprntly's PRD Page generator" in systems["a"]
    # The human-PRD flow must NOT carry the implementation-spec METHOD.
    assert "METHOD (skill: implementation-spec" not in prefixes["a"]
    assert "METHOD (skill: implementation-spec" not in systems["a"]


def test_real_gateway_spec_carries_implementation_spec_method(
    isolated_settings, monkeypatch
):
    """The on-demand spec flow's prompt carries the implementation-spec METHOD
    and is fed the finished human PRD."""
    # Seed a ready human PRD directly (no llm_call patch) so the on-demand spec
    # path drives the REAL gateway through call_md.
    _seed_corpus(isolated_settings["data_dir"])
    db_mod = isolated_settings["db"]
    brief_id = _seed_brief(db_mod)
    prd_id = _start_prd(db_mod, brief_id)
    db_mod.complete_prd(prd_id, title="t", md=_PART_A)

    systems: dict[str, str] = {}
    prefixes: dict[str, str] = {}

    def _call_md(**kwargs):
        systems["b"] = kwargs["system"]
        prefixes["b"] = kwargs.get("user_cacheable_prefix") or ""
        assert "PART A — HUMAN PRD" in kwargs["user"]
        return _PART_B

    import app.graph.gateway as gw
    monkeypatch.setattr(gw, "call_md", _call_md)
    result = prd_runner.ensure_impl_spec(prd_id)

    # The skill METHOD now rides the cacheable prefix (not the system prompt).
    assert "METHOD (skill: implementation-spec" in prefixes["b"]
    assert "Sprntly's Implementation Spec agent" in systems["b"]
    assert "Implementation Spec" in result["llm_part"]


# ── error paths (human-PRD flow) ─────────────────────────────────────────────

def test_run_sync_missing_brief_raises(isolated_settings):
    with pytest.raises(RuntimeError):
        prd_runner._run_sync(1, brief_id=9999, insight_index=0)


def test_run_sync_out_of_range_insight_raises(isolated_settings):
    db_mod = isolated_settings["db"]
    brief_id = _seed_brief(db_mod, insights=[{"title": "only-one"}])
    with pytest.raises(RuntimeError):
        prd_runner._run_sync(1, brief_id=brief_id, insight_index=5)


def test_generate_prd_records_failure_in_db(isolated_settings, monkeypatch):
    _seed_corpus(isolated_settings["data_dir"])
    db_mod = isolated_settings["db"]
    brief_id = _seed_brief(db_mod)
    prd_id = _start_prd(db_mod, brief_id)

    def _boom(**_kw):
        raise ValueError("LLM exploded")

    monkeypatch.setattr(prd_runner, "llm_call", _boom)
    asyncio.run(prd_runner.generate_prd(prd_id, brief_id, 0))

    row = db_mod.get_prd(prd_id)
    assert row["status"] == "failed"
    assert "ValueError" in (row["error"] or "")


# ── format/style exemplars (company gold-standard templates) ─────────────────

def _wire_templates(isolated_settings, monkeypatch, company_id="co-tpl"):
    """Point company_template storage at the fake db, seed a company, and make
    the runner resolve the brief's slug to that company."""
    db = isolated_settings["supabase"]
    if not db.table("companies").select("id").eq("id", company_id).execute().data:
        db.table("companies").insert(
            {"id": company_id, "slug": "asurion", "display_name": "Co"}
        ).execute()
    import app.company_template as ct
    monkeypatch.setattr(ct, "require_client", lambda: db)
    monkeypatch.setattr(prd_runner, "company_id_for_slug", lambda _slug: company_id)
    return ct


def test_templates_reach_human_prd_call(isolated_settings, monkeypatch):
    """A company's uploaded gold-standard templates are folded into the human-PRD
    call as a FORMAT/STYLE EXEMPLARS block so the PRD matches house style."""
    _seed_corpus(isolated_settings["data_dir"])
    db_mod = isolated_settings["db"]
    brief_id = _seed_brief(db_mod)
    prd_id = _start_prd(db_mod, brief_id)

    ct = _wire_templates(isolated_settings, monkeypatch)
    ct.save_company_template(
        "co-tpl", filename="gold.md", data=b"GOLD_TEMPLATE_MARK", label="House style"
    )

    call, captured = _part_a_mock()
    monkeypatch.setattr(prd_runner, "llm_call", call)
    prd_runner._run_sync(prd_id, brief_id, 0)

    assert len(captured) == 1
    assert "FORMAT/STYLE EXEMPLARS" in captured[0]["input"]
    assert "GOLD_TEMPLATE_MARK" in captured[0]["input"]
    assert "House style" in captured[0]["input"]


def test_no_templates_is_clean_no_op(isolated_settings, monkeypatch):
    """No templates uploaded ⇒ no exemplars block in the human-PRD call."""
    _seed_corpus(isolated_settings["data_dir"])
    db_mod = isolated_settings["db"]
    brief_id = _seed_brief(db_mod)
    prd_id = _start_prd(db_mod, brief_id)

    _wire_templates(isolated_settings, monkeypatch)  # company exists, but no templates

    call, captured = _part_a_mock()
    monkeypatch.setattr(prd_runner, "llm_call", call)
    prd_runner._run_sync(prd_id, brief_id, 0)

    assert "FORMAT/STYLE EXEMPLARS" not in captured[0]["input"]
    assert db_mod.get_prd(prd_id)["status"] == "ready"


def test_template_lookup_failure_does_not_break_prd(isolated_settings, monkeypatch):
    """A templates read error degrades to no exemplars — never fails the PRD."""
    _seed_corpus(isolated_settings["data_dir"])
    db_mod = isolated_settings["db"]
    brief_id = _seed_brief(db_mod)
    prd_id = _start_prd(db_mod, brief_id)

    monkeypatch.setattr(prd_runner, "company_id_for_slug", lambda _slug: "co-x")

    def _boom(*_a, **_k):
        raise RuntimeError("templates backend down")

    monkeypatch.setattr(prd_runner, "render_templates_for_prompt", _boom)

    call, captured = _part_a_mock()
    monkeypatch.setattr(prd_runner, "llm_call", call)
    prd_runner._run_sync(prd_id, brief_id, 0)

    assert db_mod.get_prd(prd_id)["status"] == "ready"
    assert "FORMAT/STYLE EXEMPLARS" not in captured[0]["input"]


# ── byline: account owner is the author when no logged-in author is supplied ──

def _seed_owner(sb, *, slug="asurion", company_id="co-asurion",
                user_id="u-owner", full_name="Dana Owner", role="owner"):
    """Seed a company owned by `full_name` so company_id_for_slug(slug) resolves
    and owner_name_for_company(company_id) returns the owner's name."""
    sb.table("companies").insert(
        {"id": company_id, "slug": slug, "display_name": slug.title()}
    ).execute()
    sb.table("company_members").insert(
        {"id": f"cm-{company_id}-{user_id}", "company_id": company_id,
         "user_id": user_id, "role": role}
    ).execute()
    sb.table("profiles").insert({"id": user_id, "full_name": full_name}).execute()
    return company_id


def test_byline_falls_back_to_account_owner_when_no_author(isolated_settings, monkeypatch):
    """A background/brief-generated PRD (author=None) puts the ACCOUNT OWNER's
    name on the byline instead of the `[NEED: author]` placeholder."""
    _seed_corpus(isolated_settings["data_dir"])
    db_mod = isolated_settings["db"]
    _seed_owner(isolated_settings["supabase"])  # "asurion" owned by Dana Owner
    brief_id = _seed_brief(db_mod)              # dataset defaults to "asurion"
    prd_id = _start_prd(db_mod, brief_id)

    call, captured = _part_a_mock()
    monkeypatch.setattr(prd_runner, "llm_call", call)
    prd_runner._run_sync(prd_id, brief_id, 0)   # sync path passes author=None

    # The byline slot (backtick-wrapped) carries the owner's name, not the
    # placeholder. (The HTML template mentions "[NEED: author]" as instruction
    # text, so assert on the backtick-wrapped byline to disambiguate.)
    directive = captured[0]["input"]
    assert "`Dana Owner`" in directive
    assert "`[NEED: author]`" not in directive


def test_explicit_author_overrides_the_owner_fallback(isolated_settings, monkeypatch):
    """A logged-in user's name (passed by the /v1/prd/generate route) still wins
    over the owner fallback."""
    _seed_corpus(isolated_settings["data_dir"])
    db_mod = isolated_settings["db"]
    _seed_owner(isolated_settings["supabase"])
    brief_id = _seed_brief(db_mod)
    prd_id = _start_prd(db_mod, brief_id)

    call, captured = _part_a_mock()
    monkeypatch.setattr(prd_runner, "llm_call", call)
    asyncio.run(prd_runner.generate_prd(prd_id, brief_id, 0, author="Logged In User"))

    directive = captured[0]["input"]
    assert "`Logged In User`" in directive
    assert "Dana Owner" not in directive


def test_byline_needs_author_when_no_owner_resolves(isolated_settings, monkeypatch):
    """No company/owner on file → the byline keeps the `[NEED: author]`
    placeholder (unchanged behaviour for ownerless/legacy datasets)."""
    _seed_corpus(isolated_settings["data_dir"])
    db_mod = isolated_settings["db"]
    brief_id = _seed_brief(db_mod)              # no company seeded for "asurion"
    prd_id = _start_prd(db_mod, brief_id)

    call, captured = _part_a_mock()
    monkeypatch.setattr(prd_runner, "llm_call", call)
    prd_runner._run_sync(prd_id, brief_id, 0)

    # The byline slot itself (backtick-wrapped) keeps the placeholder.
    assert "`[NEED: author]`" in captured[0]["input"]


def test_owner_name_for_company_prefers_owner_then_admin(isolated_settings):
    """The lookup returns the owner's name; falls back to an admin's; None for an
    unknown company."""
    from app.db.companies import owner_name_for_company

    sb = isolated_settings["supabase"]
    _seed_owner(sb, slug="acme", company_id="co-acme", user_id="u-o",
                full_name="Olivia Owner", role="owner")
    # An admin on the same company must NOT shadow the owner.
    sb.table("company_members").insert(
        {"id": "cm-co-acme-u-a", "company_id": "co-acme", "user_id": "u-a", "role": "admin"}
    ).execute()
    sb.table("profiles").insert({"id": "u-a", "full_name": "Adam Admin"}).execute()
    assert owner_name_for_company("co-acme") == "Olivia Owner"

    # Admin-only company → the admin is used.
    sb.table("companies").insert({"id": "co-noown", "slug": "noown", "display_name": "Noown"}).execute()
    sb.table("company_members").insert(
        {"id": "cm-co-noown-u-b", "company_id": "co-noown", "user_id": "u-b", "role": "admin"}
    ).execute()
    sb.table("profiles").insert({"id": "u-b", "first_name": "Amy", "last_name": "Admin"}).execute()
    assert owner_name_for_company("co-noown") == "Amy Admin"

    assert owner_name_for_company("co-missing") is None
    assert owner_name_for_company(None) is None


# ── Evidence header carries NO "View evidence page" link ──────────────────────

def test_prd_template_has_no_evidence_link():
    """The skill's HTML template renders the Evidence header as a plain label —
    no `View evidence page` link, no evidence href, no leftover `.evhead` CSS."""
    tpl = prd_runner._load_part_a_template()
    assert "View evidence page" not in tpl
    assert "app.sprntly.ai/evidence" not in tpl
    assert "evhead" not in tpl
    assert '<div class="eyebrow">Evidence</div>' in tpl


def test_part_a_directive_has_no_evidence_link_placeholder():
    """The directive no longer injects an evidence-page URL and instructs the
    model to leave the Evidence header link-free."""
    d = prd_runner._PART_A_DIRECTIVE
    assert "{evidence_page}" not in d
    assert "View evidence page" not in d
    assert "NO link" in d


def test_generated_prompt_carries_no_evidence_link(isolated_settings, monkeypatch):
    """End-to-end: the prompt sent to the model (directive + REAL template)
    contains no `View evidence page` link and no evidence URL."""
    _seed_corpus(isolated_settings["data_dir"])
    db_mod = isolated_settings["db"]
    brief_id = _seed_brief(db_mod)
    prd_id = _start_prd(db_mod, brief_id)

    call, captured = _part_a_mock()
    monkeypatch.setattr(prd_runner, "llm_call", call)
    prd_runner._run_sync(prd_id, brief_id, 0)

    prompt = captured[0]["input"]
    assert "View evidence page" not in prompt
    assert "app.sprntly.ai/evidence" not in prompt
    # The Evidence section itself is still present (just link-free).
    assert "Evidence" in prompt


# ── PRD import: faithful re-layout from an uploaded doc ───────────────────────

def test_import_mode_feeds_doc_as_source_and_skips_grounding(
    isolated_settings, monkeypatch
):
    """`import_source_md` routes the faithful-re-layout path: the uploaded doc IS
    the evidence/source (KG/corpus grounding is skipped), fed through one Part-A
    call with the faithful-re-layout instruction."""
    # A corpus exists for the dataset — the import path must NOT read it.
    _seed_corpus(isolated_settings["data_dir"])
    db_mod = isolated_settings["db"]
    brief_id = _seed_brief(db_mod)
    prd_id = _start_prd(db_mod, brief_id, title="Imported")

    call, captured = _part_a_mock()
    monkeypatch.setattr(prd_runner, "llm_call", call)

    doc = "# Uploaded PRD\n\nMUST support SSO. Target churn 8%. Unique-marker-XYZ."
    insight = {"title": "Imported", "summary": "from upload"}
    loop = asyncio.new_event_loop()
    try:
        loop.run_until_complete(
            prd_runner.generate_prd(
                prd_id, brief_id, 0,
                insight_override=insight, import_source_md=doc,
            )
        )
    finally:
        loop.close()

    # Exactly one (Part A) call; the doc text + faithful-relayout framing ride the
    # prompt, and the corpus body does NOT (grounding was skipped).
    assert len(captured) == 1
    user_input = captured[0]["input"]
    assert "Unique-marker-XYZ" in user_input
    assert "FAITHFUL RE-LAYOUT" in user_input
    assert "corpus body" not in user_input

    row = db_mod.get_prd(prd_id)
    assert row["status"] == "ready"
    assert row["title"] == "Imported"


# ── Chat-attached documents: extra_source_md layers on top of grounding ──────

def test_chat_docs_are_the_source_and_are_not_re_laid_out(isolated_settings, monkeypatch):
    """`extra_source_md` (the user's chat material) is the source for a chat PRD.

    It is still NOT the import path: the document is input to be authored FROM,
    not an existing PRD to be faithfully re-laid-out, so the re-layout framing
    must stay absent.
    """
    _seed_corpus(isolated_settings["data_dir"])
    db_mod = isolated_settings["db"]
    brief_id = _seed_brief(db_mod)
    prd_id = _start_prd(db_mod, brief_id, title="Chat task")

    call, captured = _part_a_mock()
    monkeypatch.setattr(prd_runner, "llm_call", call)

    doc = "--- requirements.pdf ---\nMUST prefill cart from deal. Doc-marker-ABC."
    insight = {"title": "Chat task", "summary": "from chat", "query": "cart prefill"}
    loop = asyncio.new_event_loop()
    try:
        loop.run_until_complete(
            prd_runner.generate_prd(
                prd_id, brief_id, 0,
                insight_override=insight, extra_source_md=doc,
            )
        )
    finally:
        loop.close()

    assert len(captured) == 1
    user_input = captured[0]["input"]
    # The user's material + its source framing are in the prompt…
    assert "Doc-marker-ABC" in user_input
    assert "SOURCE MATERIAL — THIS CONVERSATION" in user_input
    # …authored FROM, not re-laid-out (that is the import path's contract)…
    assert "FAITHFUL RE-LAYOUT" not in user_input
    # …and no workspace corpus rides along (see CHAT_SOURCE_EXCLUSIVE).
    assert "corpus body" not in user_input

    assert db_mod.get_prd(prd_id)["status"] == "ready"


def _run_chat_prd(db_mod, brief_id, prd_id, monkeypatch, doc):
    """Generate a chat-task PRD (extra_source_md set) and return the prompt."""
    call, captured = _part_a_mock()
    monkeypatch.setattr(prd_runner, "llm_call", call)
    insight = {"title": "Chat task", "summary": "from chat", "query": "car ticket"}
    loop = asyncio.new_event_loop()
    try:
        loop.run_until_complete(
            prd_runner.generate_prd(
                prd_id, brief_id, 0, insight_override=insight, extra_source_md=doc
            )
        )
    finally:
        loop.close()
    return captured[0]["input"]


_CHAT_DOC = "User: get me a ticket of car\n\nSprntly: KAN-1033 — Build a car driving feature"


def test_chat_prd_grounds_on_the_thread_alone(isolated_settings, monkeypatch):
    """With CHAT_SOURCE_EXCLUSIVE on, a chat PRD sees the user's material and
    NOTHING from the workspace.

    Reported twice: a PRD requested for Jira ticket KAN-1033 came back about the
    workspace's unrelated reconditioning/MRT theme, because retrieval matched on
    the shared word "ticket". Demoting that block below the user's material was
    not enough — its presence alone kept pulling the document off-topic — so
    retrieval is skipped for this path entirely.
    """
    assert prd_runner.CHAT_SOURCE_EXCLUSIVE is True
    _seed_corpus(isolated_settings["data_dir"])
    db_mod = isolated_settings["db"]
    brief_id = _seed_brief(db_mod)
    prd_id = _start_prd(db_mod, brief_id, title="Chat task")

    user_input = _run_chat_prd(db_mod, brief_id, prd_id, monkeypatch, _CHAT_DOC)

    # The thread is there — including the ASSISTANT's reply, which is where the
    # ticket actually lives and what used to be dropped.
    assert "SOURCE MATERIAL — THIS CONVERSATION" in user_input
    assert "KAN-1033" in user_input
    # …and the workspace corpus is nowhere in the prompt.
    assert "corpus body" not in user_input
    assert "SUPPORTING WORKSPACE CONTEXT" not in user_input
    # No DANGLING reference to a workspace block either. The first attempt told
    # the model that workspace context "supplied after this block" was background
    # only — with retrieval skipped there was no such block, and the model
    # rendered the reference literally ("[none provided]") and echoed the
    # transcript back instead of authoring a PRD.
    assert "BACKGROUND ONLY" not in user_input
    # Delimited like the import path, and told outright not to restate the chat.
    assert "--- BEGIN CONVERSATION ---" in user_input
    assert "INPUT, never output" in user_input
    assert db_mod.get_prd(prd_id)["status"] == "ready"


def test_layered_mode_still_works_when_the_flag_is_flipped_back(
    isolated_settings, monkeypatch
):
    """The experiment is reversible: with CHAT_SOURCE_EXCLUSIVE off, the user's
    material LEADS and the workspace evidence follows it as background.

    Pinned so the fallback stays working while the thread-only version is being
    evaluated — flipping one flag must be all it takes to go back.
    """
    monkeypatch.setattr(prd_runner, "CHAT_SOURCE_EXCLUSIVE", False)
    _seed_corpus(isolated_settings["data_dir"])
    db_mod = isolated_settings["db"]
    brief_id = _seed_brief(db_mod)
    prd_id = _start_prd(db_mod, brief_id, title="Chat task")

    user_input = _run_chat_prd(db_mod, brief_id, prd_id, monkeypatch, _CHAT_DOC)

    primary_at = user_input.index("PRIMARY SOURCE")
    supporting_at = user_input.index("SUPPORTING WORKSPACE CONTEXT")
    corpus_at = user_input.index("corpus body")
    # User material first, then the demoted workspace block, with the retrieved
    # evidence inside it — order matters as much as the wording.
    assert primary_at < supporting_at < corpus_at
    assert "BACKGROUND ONLY" in user_input


def test_no_chat_docs_leaves_prompt_unchanged(isolated_settings, monkeypatch):
    """extra_source_md=None (every pre-existing caller) must not inject the
    user-material framing, nor demote its own grounding."""
    _seed_corpus(isolated_settings["data_dir"])
    db_mod = isolated_settings["db"]
    brief_id = _seed_brief(db_mod)
    prd_id = _start_prd(db_mod, brief_id, title="t")

    call, captured = _part_a_mock()
    monkeypatch.setattr(prd_runner, "llm_call", call)
    prd_runner._run_sync(prd_id, brief_id, 0)

    assert "PRIMARY SOURCE" not in captured[0]["input"]
    assert "SOURCE MATERIAL — THIS CONVERSATION" not in captured[0]["input"]
    # The brief/insight paths have no competing user material, so their grounding
    # is NOT background — it is the evidence, and must not be relabelled.
    assert "SUPPORTING WORKSPACE CONTEXT" not in captured[0]["input"]


def test_part_b_receives_its_normative_skeleton(isolated_settings, monkeypatch):
    """The implementation-spec SKILL.md calls the B0-B9 skeleton NORMATIVE, but
    the gateway injects only SKILL.md / modules/ / references/ — never
    `templates/`. So until `_load_part_b_template` existed the model was told to
    conform to a structure it was never shown and rebuilt B0-B9 from prose.

    Part A never had this gap. This pins the same treatment for Part B: the
    skeleton rides the CACHEABLE prefix (byte-stable per method version, so it
    is one cache write then reads), not the per-PRD input.
    """
    _seed_corpus(isolated_settings["data_dir"])
    db_mod = isolated_settings["db"]
    brief_id = _seed_brief(db_mod)
    prd_id = _start_prd(db_mod, brief_id)

    call, captured = _part_a_mock()
    monkeypatch.setattr(prd_runner, "llm_call", call)
    asyncio.run(prd_runner.generate_prd_and_warm(prd_id, brief_id, 0))

    part_b = next(c for c in captured if c["purpose"] == "generate_prd_part_b")
    prefix = part_b.get("user_cacheable_prefix") or ""
    assert "B0. Derivation" in prefix, "the B0-B9 skeleton must reach the model"
    assert "B7" in prefix and "B9" in prefix, "the whole skeleton, not a fragment"
    # On the cacheable prefix, NOT the per-PRD input — otherwise every PRD pays
    # full price for a block that never changes.
    assert "B0. Derivation" not in (part_b.get("input") or "")


# ── the company's own uploaded PRD FORMAT (artifact_templates) ───────────────
#
# Distinct from the gold-standard EXEMPLARS above: those are additive voice
# guidance folded into `input`. This is a GOVERNING skeleton that replaces the
# vendored one in the cacheable prefix, and it is what
# `prd_runner.resolve_prd_template` picks.

_CUSTOM_SKELETON = (
    "<!DOCTYPE html><html><head><style></style></head><body>"
    '<div class="frame"><div class="page" contenteditable="true">'
    '<h1>{{title}}</h1><div class="byline">{{author}}</div>'
    '<div class="eyebrow">ACME BACKGROUND SECTION</div><p>{{context}}</p>'
    '<ul class="ev"><li>{{claim}}</li></ul>'
    '<div class="appendix"><ul class="inputs"><li>{{q}}</li></ul></div>'
    "</div></div></body></html>"
)


def _seed_format(
    isolated_settings, monkeypatch, *, company_id="co-fmt", compiled=_CUSTOM_SKELETON,
    compile_status="ready", active=True, artifact_type="prd",
):
    """Give the brief's company an uploaded PRD format in a chosen state.

    Written through the real db API so the row goes through the same
    encode/decode path generation reads it back on."""
    db = isolated_settings["supabase"]
    if not db.table("companies").select("id").eq("id", company_id).execute().data:
        db.table("companies").insert(
            {"id": company_id, "slug": "asurion", "display_name": "Co"}
        ).execute()
    monkeypatch.setattr(prd_runner, "company_id_for_slug", lambda _slug: company_id)

    from app.db.artifact_templates import (
        activate_template,
        insert_template,
        set_compile_result,
    )

    row = insert_template(
        company_id=company_id, workspace_id="ws-1", artifact_type=artifact_type,
        name="Acme PRD v3", source_md="# Acme PRD\n", content_hash="hash12345678",
        uploader_id="user-1", uploader_name="Ada",
    )
    set_compile_result(
        company_id=company_id, template_id=row["id"],
        compile_status=compile_status, compiled=compiled,
        section_map={"sections": [], "unmapped_house": [], "extra_sections": []},
        compile_notes=[],
    )
    if active:
        # activate_template gates on ownership + type only, so a row can be
        # active while `compiling` — which is exactly the recompile state.
        activate_template(company_id, artifact_type, row["id"])
    return company_id, row["id"]


def test_no_active_format_leaves_the_part_a_prompt_byte_identical(
    isolated_settings, monkeypatch
):
    """THE REGRESSION GUARD for this whole feature.

    Every company that never uploads a format — which is every company today —
    must get a prompt that is byte-for-byte what it was before this shipped.
    Not "equivalent": identical, so their prompt-cache entries survive and no
    generated PRD moves. Both halves are pinned: the system prompt carries no
    custom-format addendum, and the cacheable prefix is the vendored skeleton."""
    _seed_corpus(isolated_settings["data_dir"])
    db_mod = isolated_settings["db"]
    brief_id = _seed_brief(db_mod)
    prd_id = _start_prd(db_mod, brief_id)

    call, captured = _part_a_mock()
    monkeypatch.setattr(prd_runner, "llm_call", call)
    prd_runner._run_sync(prd_id, brief_id, 0)

    part_a = captured[0]
    assert part_a["system"] == prd_runner._SYSTEM
    assert prd_runner._CUSTOM_TEMPLATE_ADDENDUM not in part_a["system"]
    assert part_a["user_cacheable_prefix"] == prd_runner._TEMPLATE_PREFIX.format(
        template=prd_runner._load_part_a_template()
    )
    # And nothing is stamped: NULL is what "written in Sprntly's own format"
    # means, and it is what every pre-existing row already holds.
    assert db_mod.get_prd(prd_id)["artifact_template_id"] is None


def test_an_active_format_reaches_the_cacheable_prefix(isolated_settings, monkeypatch):
    _seed_corpus(isolated_settings["data_dir"])
    db_mod = isolated_settings["db"]
    brief_id = _seed_brief(db_mod)
    prd_id = _start_prd(db_mod, brief_id)
    _seed_format(isolated_settings, monkeypatch)

    call, captured = _part_a_mock()
    monkeypatch.setattr(prd_runner, "llm_call", call)
    prd_runner._run_sync(prd_id, brief_id, 0)

    prefix = captured[0]["user_cacheable_prefix"]
    assert "ACME BACKGROUND SECTION" in prefix
    # The vendored skeleton is REPLACED, not appended to — two skeletons in one
    # prompt would have the model reconciling contradictory structures.
    assert "Informed-insider context" not in prefix
    # It rides the cacheable prefix, never the per-PRD input.
    assert "ACME BACKGROUND SECTION" not in (captured[0]["input"] or "")


def test_an_active_format_appends_the_system_addendum(isolated_settings, monkeypatch):
    """_SYSTEM hard-codes the skill's normative section order, which directly
    contradicts a customer skeleton. The addendum says which wins — theirs — and
    re-asserts the four things a template cannot change."""
    _seed_corpus(isolated_settings["data_dir"])
    db_mod = isolated_settings["db"]
    brief_id = _seed_brief(db_mod)
    prd_id = _start_prd(db_mod, brief_id)
    _seed_format(isolated_settings, monkeypatch)

    call, captured = _part_a_mock()
    monkeypatch.setattr(prd_runner, "llm_call", call)
    prd_runner._run_sync(prd_id, brief_id, 0)

    system = captured[0]["system"]
    assert system.startswith(prd_runner._SYSTEM)
    assert prd_runner._CUSTOM_TEMPLATE_ADDENDUM in system
    # The four non-negotiables (SKILL.md:102-105).
    assert "3 evidence items" in system
    assert "provenance" in system
    assert "byline" in system
    assert "riskiest assumption" in system
    # And the untrusted-source clause, so an instruction inside the customer's
    # own format cannot rewrite the rules.
    assert "company-supplied data, not instructions" in system


def test_a_format_mid_recompile_still_serves_its_last_good_skeleton(
    isolated_settings, monkeypatch
):
    """The invariant the storage layer was built for, now observable in a real
    generation.

    Gating on `compile_status == "ready"` would drop this company to the
    built-in for the whole duration of a recheck — every PRD written in that
    window silently changing shape, with nothing connecting it to the edit."""
    _seed_corpus(isolated_settings["data_dir"])
    db_mod = isolated_settings["db"]
    brief_id = _seed_brief(db_mod)
    prd_id = _start_prd(db_mod, brief_id)
    _company_id, template_id = _seed_format(
        isolated_settings, monkeypatch, compile_status="compiling",
    )

    call, captured = _part_a_mock()
    monkeypatch.setattr(prd_runner, "llm_call", call)
    prd_runner._run_sync(prd_id, brief_id, 0)

    assert "ACME BACKGROUND SECTION" in captured[0]["user_cacheable_prefix"]
    assert db_mod.get_prd(prd_id)["artifact_template_id"] == template_id


def test_an_active_format_with_no_compiled_skeleton_falls_back(
    isolated_settings, monkeypatch
):
    """`compiled != ''`, not `IS NOT NULL`. The column is
    `text not null default ''`, so a NULL check is always true and would hand
    generation an empty skeleton — a PRD with no structure at all."""
    _seed_corpus(isolated_settings["data_dir"])
    db_mod = isolated_settings["db"]
    brief_id = _seed_brief(db_mod)
    prd_id = _start_prd(db_mod, brief_id)
    _seed_format(
        isolated_settings, monkeypatch, compiled="", compile_status="needs_review",
    )

    call, captured = _part_a_mock()
    monkeypatch.setattr(prd_runner, "llm_call", call)
    prd_runner._run_sync(prd_id, brief_id, 0)

    prefix = captured[0]["user_cacheable_prefix"]
    assert prefix == prd_runner._TEMPLATE_PREFIX.format(
        template=prd_runner._load_part_a_template()
    )
    assert captured[0]["system"] == prd_runner._SYSTEM
    assert db_mod.get_prd(prd_id)["status"] == "ready"
    assert db_mod.get_prd(prd_id)["artifact_template_id"] is None


def test_an_inactive_format_is_ignored(isolated_settings, monkeypatch):
    # Uploading and checking a format changes nothing until an admin activates
    # it. A ready-but-inactive row must not leak into generation.
    _seed_corpus(isolated_settings["data_dir"])
    db_mod = isolated_settings["db"]
    brief_id = _seed_brief(db_mod)
    prd_id = _start_prd(db_mod, brief_id)
    _seed_format(isolated_settings, monkeypatch, active=False)

    call, captured = _part_a_mock()
    monkeypatch.setattr(prd_runner, "llm_call", call)
    prd_runner._run_sync(prd_id, brief_id, 0)

    assert "ACME BACKGROUND SECTION" not in captured[0]["user_cacheable_prefix"]
    assert db_mod.get_prd(prd_id)["artifact_template_id"] is None


def test_a_ticket_format_never_governs_a_prd(isolated_settings, monkeypatch):
    # The lookup is keyed on (company, artifact_type). An active TICKET format
    # must not be handed to the PRD generator.
    _seed_corpus(isolated_settings["data_dir"])
    db_mod = isolated_settings["db"]
    brief_id = _seed_brief(db_mod)
    prd_id = _start_prd(db_mod, brief_id)
    _seed_format(isolated_settings, monkeypatch, artifact_type="tickets")

    call, captured = _part_a_mock()
    monkeypatch.setattr(prd_runner, "llm_call", call)
    prd_runner._run_sync(prd_id, brief_id, 0)

    assert "ACME BACKGROUND SECTION" not in captured[0]["user_cacheable_prefix"]


def test_a_format_lookup_failure_degrades_to_the_builtin(
    isolated_settings, monkeypatch
):
    """Fail OPEN, like skills/resolver.py. An uploaded format is a
    nice-to-have; a PRD that fails because a lookup hiccuped is not."""
    _seed_corpus(isolated_settings["data_dir"])
    db_mod = isolated_settings["db"]
    brief_id = _seed_brief(db_mod)
    prd_id = _start_prd(db_mod, brief_id)
    monkeypatch.setattr(prd_runner, "company_id_for_slug", lambda _slug: "co-x")

    def _boom(*_a, **_k):
        raise RuntimeError("artifact_templates backend down")

    monkeypatch.setattr(prd_runner, "get_active_template", _boom)

    call, captured = _part_a_mock()
    monkeypatch.setattr(prd_runner, "llm_call", call)
    prd_runner._run_sync(prd_id, brief_id, 0)

    assert captured[0]["user_cacheable_prefix"] == prd_runner._TEMPLATE_PREFIX.format(
        template=prd_runner._load_part_a_template()
    )
    # The PRD still lands. That is the whole point of failing open.
    assert db_mod.get_prd(prd_id)["status"] == "ready"


def test_a_failed_provenance_stamp_never_fails_a_finished_prd(
    isolated_settings, monkeypatch
):
    # The document is written and readable; losing the record of WHICH format
    # wrote it must not turn a ready PRD into a failed one.
    _seed_corpus(isolated_settings["data_dir"])
    db_mod = isolated_settings["db"]
    brief_id = _seed_brief(db_mod)
    prd_id = _start_prd(db_mod, brief_id)
    _seed_format(isolated_settings, monkeypatch)

    def _boom(*_a, **_k):
        raise RuntimeError("update failed")

    monkeypatch.setattr(prd_runner, "set_prd_artifact_template", _boom)

    call, _captured = _part_a_mock()
    monkeypatch.setattr(prd_runner, "llm_call", call)
    prd_runner._run_sync(prd_id, brief_id, 0)

    assert db_mod.get_prd(prd_id)["status"] == "ready"


def test_activating_another_format_mid_run_does_not_change_the_generation(
    isolated_settings, monkeypatch
):
    """`_build_context` resolves the format ONCE and threads it through ctx, so
    a run finishes in the format it started in. Free — deliberately not a lock."""
    _seed_corpus(isolated_settings["data_dir"])
    db_mod = isolated_settings["db"]
    brief_id = _seed_brief(db_mod)
    prd_id = _start_prd(db_mod, brief_id)
    company_id, first_id = _seed_format(isolated_settings, monkeypatch)

    from app.db.artifact_templates import (
        activate_template,
        insert_template,
        set_compile_result,
    )

    # A SECOND format, activated from inside the model call — i.e. after the
    # context was built and before the PRD is finalized.
    second = insert_template(
        company_id=company_id, workspace_id="ws-1", artifact_type="prd",
        name="Acme PRD v4", source_md="# v4\n", content_hash="hash87654321",
        uploader_id="user-1", uploader_name="Ada",
    )
    set_compile_result(
        company_id=company_id, template_id=second["id"], compile_status="ready",
        compiled="<html>SECOND FORMAT</html>", section_map={}, compile_notes=[],
    )

    captured: list = []

    def _call(**kwargs):
        captured.append(kwargs)
        activate_template(company_id, "prd", second["id"])
        return _llm_result(_PART_A)

    monkeypatch.setattr(prd_runner, "llm_call", _call)
    prd_runner._run_sync(prd_id, brief_id, 0)

    # Generated in the first format...
    assert "ACME BACKGROUND SECTION" in captured[0]["user_cacheable_prefix"]
    assert "SECOND FORMAT" not in captured[0]["user_cacheable_prefix"]
    # ...and STAMPED with the first, not with whatever became active meanwhile.
    assert db_mod.get_prd(prd_id)["artifact_template_id"] == first_id


def test_resolve_prd_template_without_a_company_is_the_builtin(isolated_settings):
    # Legacy corpus datasets own no company row. No company => no DB read at all.
    template, template_id = prd_runner.resolve_prd_template(None)
    assert template == prd_runner._load_part_a_template()
    assert template_id is None


# ── the company's own uploaded ENGINEERING-SPEC format (Part B) ──────────────
#
# The markdown twin of the PRD-format block above. Part B has no structured
# viewer and no class vocabulary; the only thing a customer's format must not
# cost us is the B0-B9 ids, which `stories/generate.py` reads to inherit ticket
# acceptance criteria.

_CUSTOM_SPEC_SKELETON = (
    "# Engineering Spec — {{title}}\n"
    "## B0. Where this came from\n{{derivation}}\n"
    "## B1. Background for the agent\n{{context}}\n"
    "## B2. Stakes\n{{stakes}}\n"
    "## B3. ACME BEHAVIOUR RULES\n{{ears}}\n"
    "## B4. Contracts\n{{contracts}}\n"
    "## B5. Escalations\n{{escalations}}\n"
    "## B6. Cross-cutting\n{{crosscutting}}\n"
    "## B7. Work breakdown\n{{tasks}}\n"
    "## B8. How we know it's done\n{{acceptance}}\n"
    "## B9. Independent check\n{{verification}}\n"
)


def _part_b_call(captured):
    """The Part B call out of a full generate-and-warm run."""
    return next(c for c in captured if c["purpose"] == "generate_prd_part_b")


def test_no_active_spec_format_leaves_the_part_b_prompt_byte_identical(
    isolated_settings, monkeypatch
):
    """THE REGRESSION GUARD for this milestone.

    Every company that never uploads an engineering-spec format — which is
    every company today — must get a Part B prompt that is byte-for-byte what
    it was before this shipped. Not "equivalent": identical, so their
    prompt-cache entries survive and no generated spec moves. Both halves are
    pinned: the system prompt carries no custom-format addendum, and the
    cacheable prefix is the vendored B0-B9 skeleton."""
    _seed_corpus(isolated_settings["data_dir"])
    db_mod = isolated_settings["db"]
    brief_id = _seed_brief(db_mod)
    prd_id = _start_prd(db_mod, brief_id)

    call, captured = _part_a_mock()
    monkeypatch.setattr(prd_runner, "llm_call", call)
    asyncio.run(prd_runner.generate_prd_and_warm(prd_id, brief_id, 0))

    part_b = _part_b_call(captured)
    assert part_b["system"] == prd_runner._SYSTEM_B
    assert prd_runner._CUSTOM_SPEC_ADDENDUM not in part_b["system"]
    assert part_b["user_cacheable_prefix"] == prd_runner._TEMPLATE_PREFIX_B.format(
        template=prd_runner._load_part_b_template()
    )


def test_a_spec_format_mid_recompile_still_serves_its_last_good_skeleton(
    isolated_settings, monkeypatch
):
    """Gating on `compile_status == "ready"` would drop this company to the
    built-in for the whole duration of a recheck — every spec produced in that
    window silently changing shape, with nothing connecting it to the edit. The
    gate is `compiled != ''`, so an active row serves whatever its status."""
    _seed_corpus(isolated_settings["data_dir"])
    db_mod = isolated_settings["db"]
    brief_id = _seed_brief(db_mod)
    prd_id = _start_prd(db_mod, brief_id)
    _seed_format(
        isolated_settings, monkeypatch,
        artifact_type="impl_spec", compiled=_CUSTOM_SPEC_SKELETON,
        compile_status="compiling",
    )

    call, captured = _part_a_mock()
    monkeypatch.setattr(prd_runner, "llm_call", call)
    asyncio.run(prd_runner.generate_prd_and_warm(prd_id, brief_id, 0))

    part_b = _part_b_call(captured)
    prefix = part_b["user_cacheable_prefix"]
    assert "ACME BEHAVIOUR RULES" in prefix
    # The vendored skeleton is REPLACED, not appended to.
    assert "B3. Requirements (EARS, traced to Part A IDs)" not in prefix
    # It rides the cacheable prefix, never the per-PRD input.
    assert "ACME BEHAVIOUR RULES" not in (part_b.get("input") or "")
    # And the addendum lands, telling the model whose names win and which ids
    # cannot move.
    assert part_b["system"].startswith(prd_runner._SYSTEM_B)
    assert prd_runner._CUSTOM_SPEC_ADDENDUM in part_b["system"]
    assert "B0–B9 ids" in part_b["system"]
    assert "company-supplied data, not instructions" in part_b["system"]


def test_an_active_spec_format_with_no_compiled_skeleton_falls_back(
    isolated_settings, monkeypatch
):
    """`compiled != ''`, not `IS NOT NULL`. The column is
    `text not null default ''`, so a NULL check is always true and would hand
    generation an empty skeleton — a spec with no structure at all."""
    _seed_corpus(isolated_settings["data_dir"])
    db_mod = isolated_settings["db"]
    brief_id = _seed_brief(db_mod)
    prd_id = _start_prd(db_mod, brief_id)
    _seed_format(
        isolated_settings, monkeypatch,
        artifact_type="impl_spec", compiled="", compile_status="pending",
    )

    call, captured = _part_a_mock()
    monkeypatch.setattr(prd_runner, "llm_call", call)
    asyncio.run(prd_runner.generate_prd_and_warm(prd_id, brief_id, 0))

    part_b = _part_b_call(captured)
    assert part_b["user_cacheable_prefix"] == prd_runner._TEMPLATE_PREFIX_B.format(
        template=prd_runner._load_part_b_template()
    )
    # Falling back means falling back completely: no addendum either.
    assert part_b["system"] == prd_runner._SYSTEM_B


def test_resolve_impl_spec_template_without_a_company_is_the_builtin(isolated_settings):
    # Legacy corpus datasets own no company row. No company => no DB read at all.
    template, template_id = prd_runner.resolve_impl_spec_template(None)
    assert template == prd_runner._load_part_b_template()
    assert template_id is None


def test_a_prd_format_never_answers_for_the_engineering_spec(
    isolated_settings, monkeypatch
):
    """The two libraries are separate per artifact_type. A company with an
    active PRD format and no spec format still gets the built-in B0-B9."""
    _seed_format(isolated_settings, monkeypatch, artifact_type="prd")
    template, template_id = prd_runner.resolve_impl_spec_template("co-fmt")
    assert template == prd_runner._load_part_b_template()
    assert template_id is None
