"""Background PRD generation. Triggered when a user clicks 'Generate PRD';
the HTTP request returns immediately with a prd_id and status='generating',
the actual Claude call runs in a worker thread, and the prds row gets
updated to status='ready' (or 'failed') when done.

Re-platformed onto the `prd-author` skill (the canonical 2-part method): the
skill METHOD — Part A a human-readable PRD, a horizontal rule, then Part B an
LLM-readable Implementation Spec — is bound via the gateway (`skill=`), so the
agent-specific context (the brief insight being turned into a PRD, plus the
evidence it was derived from) is the only thing the runner supplies as input.

Performance (2-part concurrent generation): rather than ONE big sequential
`llm_call` that emits both halves and then splitting on the `---` rule, the
runner now issues TWO concurrent `prd-author` calls that share the SAME
brief-insight context + KG grounding:
  - Call A → produces ONLY Part A (the human-readable PRD).
  - Call B → produces ONLY Part B (the LLM-readable Implementation Spec).
Both stay coherent (same brief, same insight, same KG facts, same template);
each is steered to emit just its half via a per-part directive layered on the
shared `prd-author` skill binding (so the METHOD + version pin are preserved).
The two calls run concurrently (`asyncio.gather` over `asyncio.to_thread`,
since the gateway's `llm_call` is synchronous), so wall-clock is ~max(A, B)
instead of A+B — roughly a 2× speedup.

Grounding is regrounded on the KNOWLEDGE GRAPH (consistent with brief/evidence/
ask, which all answer from the brain): instead of dumping the per-dataset
markdown corpus, the runner resolves the insight's KG evidence trail
(insight → theme → synthesis-written hypothesis → SUPPORTS signals + theme
convergence signals, each with content/source_type/provenance/confidence) via
`graph.retrieval.insight_evidence_trail` and feeds THAT as the grounding. The
PRD's problem/evidence section then cites the actual data-source signals that
also back the brief insight.

Resilient: KG-first-with-fallback — if the insight has no KG backing (empty
trail), the runner falls back to the corpus grounding so a PRD never
hard-fails.

Assembly + resilience:
  - Part A output → `payload_md`  — what the frontend renders, unchanged.
  - Part B output → `llm_part`    — for downstream coding-agent consumption.
  Part A is the required half: if Part B comes back empty (degenerate output),
  the PRD still completes with Part A + an empty `llm_part` (mirroring the old
  `_split_2part` resilience). If Part B's CALL fails outright, the PRD still
  completes with Part A + empty `llm_part`, and the Part-B failure is logged
  (never silent). A Part-A failure fails the whole PRD.

The generation is decision-logged (§4d) with the prd-author skill id + hash
(which the gateway pins into `prompt_version`, `+prd-author@<hash>`, taken from
the Part-A call so the audit row pins one consistent method version) plus
`kg_refs` = the signal/hypothesis/theme ids the trail surfaced and
`has_llm_part` reflecting whether Part B was produced.
"""
import asyncio
import json
import logging
import time
import uuid

from app.company_template import render_templates_for_prompt
from app.config import settings
from app.corpus import load_corpus, load_prd_template
from app.db import complete_prd_2part, get_brief_by_id
from app.db.companies import company_id_for_slug
from app.db.prds import fail_prd, find_existing_prd, start_prd
from app.graph.decision_log import log_agent_decision
from app.graph.facade import GraphFacade
from app.graph.gateway import llm_call
from app.graph.retrieval import insight_evidence_trail, render_evidence_trail_section
from app.prompts import VOICE_GUARD

logger = logging.getLogger(__name__)

PROMPT_VERSION = "prd-author-v2"
_SKILL = "prd-author"
# Part B is now generated by the dedicated `implementation-spec` skill, fed the
# FINISHED human PRD (Part A) — its method (EARS requirements, design/contracts,
# dependency-ordered tasks, acceptance tests, DoD, independent verification) is
# richer than the prd-author Part-B directive it replaces. Because it consumes
# the whole Part A, Part B runs AFTER Part A (chained), not concurrently.
_SKILL_B = "implementation-spec"
PROMPT_VERSION_B = "prd-impl-spec-v1"
_AGENT = "prd"
# Storage variant for new PRD rows — shared by the on-demand route
# (routes/prd.py) and pre-warming below, so dedupe matches across both paths.
PRD_VARIANT = "v2"

# Agent-specific framing for Part A (the human PRD). The prd-author METHOD is
# supplied by the bound skill; this system prompt states the agent's job +
# grounding rules and adds the _PART_A_DIRECTIVE so the model emits only the
# human PRD half. Part B (the Implementation Spec) is a SEPARATE, chained call
# bound to the `implementation-spec` skill with its own _SYSTEM_B (below) — it
# is fed the finished Part A, not steered by a directive.
_SYSTEM = """\
You are Sprntly's PRD agent. Following the METHOD above, turn the supplied \
brief insight into the prd-author two-part deliverable: Part A a \
human-readable PRD, and Part B an LLM-readable Implementation Spec a coding \
agent builds and tests against. You will be asked to produce exactly ONE of \
the two parts on this call — honor the PART DIRECTIVE in the request.

Ground every numeric claim, mechanism, metric, and acceptance criterion in \
the supplied insight and the evidence it was derived from — falsifiable by a \
reader who can pull the same data. The evidence is the company's \
connected-source signals (the same trail that backs the brief insight) when \
present, else the company's source data. Cite signals by source_type (and \
provenance where present). Never invent numbers, users, sources, business \
rules, or contracts; label unknowns per the METHOD (`[ASSUMPTION]` / \
`[ASSUMPTION → T0]` / `[ESCALATE]`) rather than guessing.

Emit Markdown only — no commentary outside the document. Produce ONLY the \
part named in the PART DIRECTIVE; do NOT emit the other part and do NOT emit \
the `---` horizontal rule that would separate them.""" + VOICE_GUARD

# Per-part directives. Each call carries the SAME shared context (insight +
# evidence + template) plus exactly one of these so the model emits one half.
# Part A and Part B derive from the same brief, so they stay coherent.
_PART_A_DIRECTIVE = """\
PART DIRECTIVE: Produce ONLY Part A — the human-readable Product Requirements \
Document. Render it as the typed semantic `:::` blocks defined in the TEMPLATE \
below (`:::context-chip`, `:::tldr`, `:::problem`, `:::hypothesis`, \
`:::requirements`, `:::acceptance-criteria`, `:::metrics`, `:::risks`, \
`:::milestones`, `:::dod`), in the template's order, with the prose Context \
section as written. The METHOD above governs your REASONING and quality bar \
(problem-first, no fabrication, EARS-grade requirements, Given/When/Then \
acceptance criteria, guardrail metrics, a testable done-gate); the TEMPLATE \
governs the OUTPUT FORMAT. Emit every named block EXACTLY — never a paragraph, \
bullet list, or markdown table where the template specifies a `:::` block, or \
the frontend cannot render it as a first-class component. Fill each placeholder \
with concrete, grounded content; never keep a `[bracketed]` example. Do NOT \
include Part B (the Implementation Spec), do NOT emit the `---` separator, and \
do NOT emit the template's trailing "How to use this template" section. Start \
at the document title."""

_USER_TEMPLATE = """\
{part_directive}

Write your assigned part of the two-part PRD for the following brief insight.

BRIEF INSIGHT (the problem to turn into a PRD):
{insight_json}

{evidence}
{exemplars}
TEMPLATE (the full two-part structure — produce ONLY your assigned part of it):
{template}
"""

# Part B is generated by the `implementation-spec` skill (its SKILL.md is the
# METHOD layer). Unlike Part A, it is fed the FINISHED human PRD — the skill
# consumes the PRD's tagged requirements (untagged = happy path; `[edge case]`
# / `[failure]` inline) and turns them into the LLM-readable spec.
_SYSTEM_B = """\
You are Sprntly's Implementation Spec agent. Following the METHOD above \
(the implementation-spec skill), turn the supplied human PRD into the \
LLM-readable Implementation Spec a coding agent can build and test against \
without ambiguity: EARS requirements traced to the PRD, design & contracts, \
dependency-ordered tasks, acceptance tests, a Definition of Done, and the \
independent verification report.

Consume ONLY the supplied PRD and evidence. Every requirement traces to a PRD \
goal; every contract binds verbatim to the PRD or evidence. Never invent a \
requirement, rule, or contract — split unknowns into research-resolvable \
(`[ASSUMPTION → T0]`) vs must-escalate (`[ESCALATE]`) per the METHOD. Inherit \
the PRD's load-bearing tags: untagged requirements are the happy path, \
`[edge case]` and `[failure]` requirements get their mandatory branches.

Emit Markdown only — no commentary outside the document, and do NOT restate \
Part A (the human PRD) or emit a `---` separator. Start at the Part B \
heading.""" + VOICE_GUARD

_USER_TEMPLATE_B = """\
Produce the LLM-readable Implementation Spec (Part B) for the human PRD below. \
Derive every requirement, contract, task, and acceptance test from this PRD \
and its evidence — trace each back to the PRD it implements.

HUMAN PRD (Part A — the spec to implement):
{human_prd}

{evidence}
{exemplars}"""

# Header for the source-data fallback block (KG trail unavailable / empty).
# Reader-facing wording deliberately avoids "corpus" — the model sees this
# header and must never echo internal vocabulary (see VOICE_GUARD).
_CORPUS_BLOCK = (
    "SOURCE DATA (the evidence the insight was derived from — ground claims here):\n"
    "{corpus}"
)

# The horizontal rule the prd-author skill historically emitted between Part A
# (human PRD) and Part B (Implementation Spec). The concurrent path produces the
# two parts directly (no rule to split on), but `_split_2part` is retained for
# back-compat with any caller that still consumes a single combined document.
_PART_SEPARATOR = "\n---\n"


def _split_2part(md: str) -> tuple[str, str]:
    """Split a single combined prd-author document into (Part A, Part B).

    Retained for back-compat: the concurrent generation path produces the two
    halves directly and does NOT call this. Any caller still holding a single
    combined document (Part A + `---` + Part B) can split it here. If no rule is
    present (degenerate single-part output), Part A is the whole document and
    Part B is empty.
    """
    idx = md.find(_PART_SEPARATOR)
    if idx == -1:
        return md.strip(), ""
    part_a = md[:idx].strip()
    part_b = md[idx + len(_PART_SEPARATOR):].strip()
    return part_a, part_b


def _corpus_grounding(dataset: str) -> str:
    """Corpus fallback grounding: the per-dataset markdown corpus, as a
    labelled block. Used when the KG trail is empty (no KG backing for the
    insight, a legacy corpus dataset, or any KG read error)."""
    corpus = load_corpus(dataset)
    return _CORPUS_BLOCK.format(corpus=corpus.joined())


def _kg_trail(dataset: str, brief: dict, insight_index: int) -> dict | None:
    """Best-effort KG evidence trail for the insight. Returns the trail dict
    (when it has KG backing) or None when there's no tenant context, the trail
    is empty, or any read fails — the caller then grounds on the corpus.

    Resilient by construction: a slug that owns no company, an empty KG, a fake
    backend with no pgvector, or any read error all collapse to None so the PRD
    falls back to the corpus grounding (never hard-fails)."""
    company_id = company_id_for_slug(dataset)
    if not company_id:
        logger.info("PRD KG grounding: no company for slug=%s — corpus fallback", dataset)
        return None
    try:
        facade = GraphFacade()
        trail = insight_evidence_trail(facade, company_id, brief, insight_index)
    except Exception:  # noqa: BLE001 — KG read must never break PRD generation
        logger.exception("PRD KG grounding failed for slug=%s — corpus fallback", dataset)
        return None
    if not trail or trail.get("empty"):
        return None
    return trail


def _resolve_grounding(
    dataset: str, brief: dict, insight_index: int
) -> tuple[str, dict | None]:
    """Resolve the evidence block + (the KG trail it came from, or None).

    KG-first, consistent with brief/evidence/ask: the insight's evidence trail
    when it has backing, else corpus fallback (an empty KG, a legacy corpus
    dataset, or any KG read error). The returned trail (None on the corpus
    fallback) drives kg_refs in the decision log.
    """
    trail = _kg_trail(dataset, brief, insight_index)
    if trail is not None:
        return render_evidence_trail_section(trail), trail
    return _corpus_grounding(dataset), None


def _build_context(brief_id: int, insight_index: int) -> dict:
    """Resolve everything BOTH part-calls share, exactly once.

    Returns the shared inputs for the two concurrent prd-author calls: the
    resolved company id, the evidence block + KG trail (so Part A and Part B are
    grounded on the SAME facts), the rendered template, the insight, and the
    title. Building this once guarantees the two halves are coherent.
    """
    brief = get_brief_by_id(brief_id)
    if not brief:
        raise RuntimeError(f"brief_id={brief_id} not found")
    insights = brief.get("insights") or []
    if not (0 <= insight_index < len(insights)):
        raise RuntimeError(
            f"insight_index={insight_index} out of range (0..{len(insights) - 1})"
        )
    insight = insights[insight_index]
    dataset = brief.get("dataset", "asurion")
    # The decision log is tenant-scoped by company UUID, not the dataset slug.
    # Resolve it once; a dataset that owns no company (legacy corpus datasets)
    # yields None and the §4d decision log is skipped below.
    company_id = company_id_for_slug(dataset)
    # Reground on the KG evidence trail (synthesis engine) — the same signals
    # that back the brief insight — falling back to the corpus when there's no
    # KG backing or under the legacy engine. `trail` (None on the corpus path)
    # carries the kg_refs for the decision log. Resolved ONCE and shared by both
    # part-calls so Part A and Part B cite the same evidence.
    evidence, trail = _resolve_grounding(dataset, brief, insight_index)
    # Part A (the human PRD the user reads) is generated against the typed-
    # `:::`-block contract (data/sprntly_prd_template.md) that the frontend
    # `prd-adapter` parses into first-class components (hero/metrics/
    # requirements/acceptance-criteria/…). The prd-author skill stays bound on
    # the Part-A call for its METHOD + version pin; only the OUTPUT SHAPE comes
    # from this template. Without these blocks the adapter degrades to plain
    # markdown — the "PRD looks like a raw .md" failure. (Part B is generated
    # separately by the implementation-spec skill and does NOT use this template.)
    template = load_prd_template()
    title = insight.get("title") or f"Insight #{insight_index + 1}"
    # FORMAT/STYLE EXEMPLARS — the company's uploaded gold-standard PRD examples
    # ("what good looks like"). Additive context ONLY: when the company has
    # uploaded templates, their extracted text is folded into BOTH part-calls so
    # the model MATCHES the house structure & voice. No templates (or no company
    # for the slug) ⇒ empty string ⇒ a clean no-op (the prompt is unchanged from
    # before). Best-effort: a read error must never break PRD generation.
    exemplars = ""
    if company_id:
        try:
            exemplars = render_templates_for_prompt(company_id)
        except Exception:  # noqa: BLE001 — exemplars are best-effort context
            logger.exception(
                "PRD format exemplars lookup failed for company=%s — skipping",
                company_id,
            )
            exemplars = ""
    return {
        "company_id": company_id,
        "dataset": dataset,
        "evidence": evidence,
        "trail": trail,
        "template": template,
        "exemplars": exemplars,
        "insight": insight,
        "title": title,
    }


def _call_part(ctx: dict, *, purpose: str, directive: str, background: bool = False):
    """One prd-author call that emits a single part.

    Shares `ctx`'s insight + evidence + template across both parts and steers
    the model to one half via `directive`. Keeps `skill=_SKILL` so the METHOD
    and its `+prd-author@<hash>` version pin are preserved on every call.
    """
    # Exemplars (the company's gold-standard PRD format references) slot in
    # between the evidence and the template when present; empty string ⇒ no-op.
    exemplars = ctx.get("exemplars") or ""
    exemplars_block = f"\n{exemplars}\n" if exemplars else ""
    user = _USER_TEMPLATE.format(
        part_directive=directive,
        insight_json=json.dumps(ctx["insight"], indent=2),
        evidence=ctx["evidence"],
        exemplars=exemplars_block,
        template=ctx["template"],
    )
    return llm_call(
        enterprise_id=ctx["company_id"] or ctx["dataset"],
        agent=_AGENT,
        purpose=purpose,
        prompt_version=PROMPT_VERSION,
        system=_SYSTEM,
        input=user,
        skill=_SKILL,
        background=background,
    )


def _call_part_a(ctx: dict, background: bool = False):
    """Concurrent call A — ONLY the human-readable PRD (Part A)."""
    return _call_part(
        ctx, purpose="generate_prd_part_a", directive=_PART_A_DIRECTIVE,
        background=background,
    )


def _call_part_b(ctx: dict, human_prd: str, background: bool = False):
    """Chained call B — the LLM Implementation Spec, via the `implementation-spec`
    skill, fed the FINISHED human PRD (Part A). Runs AFTER Part A because the
    skill consumes the whole PRD; binds `skill=_SKILL_B` so its METHOD + the
    `+implementation-spec@<hash>` version pin apply."""
    exemplars = ctx.get("exemplars") or ""
    exemplars_block = f"\n{exemplars}\n" if exemplars else ""
    user = _USER_TEMPLATE_B.format(
        human_prd=human_prd,
        evidence=ctx["evidence"],
        exemplars=exemplars_block,
    )
    return llm_call(
        enterprise_id=ctx["company_id"] or ctx["dataset"],
        agent=_AGENT,
        purpose="generate_prd_part_b",
        prompt_version=PROMPT_VERSION_B,
        system=_SYSTEM_B,
        input=user,
        skill=_SKILL_B,
        background=background,
    )


def _finalize(prd_id: int, brief_id: int, insight_index: int, ctx: dict,
              result_a, result_b, part_b_error: str | None) -> None:
    """Assemble the two part-outputs, persist, and decision-log.

    Part A is required (its result is always present here). Part B is best-
    effort: an empty Part-B output OR a Part-B call failure (`part_b_error`)
    both complete the PRD with Part A + an empty `llm_part` — mirroring the old
    degenerate-output resilience — and the failure (if any) is logged, never
    silent.
    """
    human_part = str(result_a.output).strip()
    if result_b is not None:
        llm_part = str(result_b.output).strip()
    else:
        llm_part = ""
    if part_b_error:
        # Part A succeeded but Part B did not — complete with Part A alone
        # (the human PRD is valid on its own) and surface the failure.
        logger.error(
            "PRD Part B generation failed prd_id=%s — completing with Part A only: %s",
            prd_id, part_b_error,
        )

    title = ctx["title"]
    complete_prd_2part(
        prd_id=prd_id, title=title, human_md=human_part, llm_part=llm_part
    )

    # Decision-log the generation (§4d). `result_a.prompt_version` carries the
    # `+prd-author@<hash>` suffix the gateway appended; both part-calls bind the
    # same skill so they pin the same hash — the audit row records the Part-A
    # one consistently. `has_llm_part` reflects whether Part B was produced.
    # kg_refs: the signal/hypothesis/theme ids the evidence trail surfaced, so
    # the §4d audit row pins the exact KG nodes this PRD was grounded on (empty
    # on the corpus-fallback path, where `trail` is None).
    trail = ctx["trail"]
    company_id = ctx["company_id"]
    kg_refs = (trail or {}).get("kg_refs") or []
    if company_id:
        factors = {
            "prd_id": prd_id,
            "brief_id": brief_id,
            "insight_index": insight_index,
            # Part A and Part B are now two different skills (the human PRD via
            # prd-author, the Implementation Spec via implementation-spec).
            "skill": _SKILL,
            "skill_part_a": _SKILL,
            "skill_part_b": _SKILL_B,
            # Part B's version pin (`+implementation-spec@<hash>`); None if Part B
            # failed and produced no result.
            "part_b_prompt_version": (
                result_b.prompt_version if result_b is not None else None
            ),
            "has_llm_part": bool(llm_part),
            "grounding": "kg" if trail is not None else "corpus",
            "kg_signals": len((trail or {}).get("signals") or []),
            # Record whether Part B failed (None on success) so the audit row
            # never hides a half-complete generation.
            "part_b_error": part_b_error,
        }
        log_agent_decision(
            enterprise_id=company_id,
            agent=_AGENT,
            decision_type="generate_prd",
            factors=factors,
            output={"title": title, "prd_id": prd_id},
            model=result_a.model,
            prompt_version=result_a.prompt_version,
            kg_refs=kg_refs,
        )


async def _generate_2part(
    prd_id: int, brief_id: int, insight_index: int, background: bool = False,
    human_only: bool = False,
) -> None:
    """Build shared context, run Part A then (chained) Part B, finalize.

    Part B is now the `implementation-spec` skill, which consumes the FINISHED
    human PRD — so the two halves can no longer run concurrently. Part A runs
    first; the moment it resolves, Part B is fed its output. Wall-clock is
    A + B (the cost of the dedicated spec skill), run as clean async (the event
    loop is never blocked — each synchronous `llm_call` runs in a worker
    thread). Part A is required (its failure fails the whole PRD); Part B is
    best-effort (its failure is captured and the PRD completes with Part A only).

    `human_only=True` generates ONLY the human PRD (Part A) and skips the
    implementation-spec call entirely — used by prefetch warming, which only
    needs the human-readable PRD ready before the user opens the brief. The
    PRD completes with an empty `llm_part`, exactly as a Part-B failure would.
    """
    ctx = await asyncio.to_thread(_build_context, brief_id, insight_index)

    # Part A first — required. A failure here fails the whole PRD.
    result_a = await asyncio.to_thread(_call_part_a, ctx, background)
    human_prd = str(result_a.output).strip()

    # Part B (implementation-spec), fed the finished Part A. Best-effort: its
    # failure is captured and the PRD still completes with Part A only. Skipped
    # entirely when human_only (prefetch warm needs only the human PRD).
    part_b_error: str | None = None
    result_b = None
    if not human_only:
        try:
            result_b = await asyncio.to_thread(
                _call_part_b, ctx, human_prd, background
            )
        except Exception as exc:  # noqa: BLE001 — Part B is best-effort
            part_b_error = f"{type(exc).__name__}: {exc}"

    await asyncio.to_thread(
        _finalize, prd_id, brief_id, insight_index, ctx,
        result_a, result_b, part_b_error,
    )


def _run_sync(prd_id: int, brief_id: int, insight_index: int) -> None:
    """Synchronous entry point (used by tests and any sync caller).

    Drives the concurrent two-part generation to completion. `generate_prd`
    calls `_generate_2part` directly on the running loop; this wrapper exists
    for sync callers and runs it on a fresh loop.
    """
    asyncio.run(_generate_2part(prd_id, brief_id, insight_index))


async def generate_prd(
    prd_id: int, brief_id: int, insight_index: int, background: bool = False,
    human_only: bool = False,
) -> None:
    """Run the concurrent two-part PRD generation; update DB with result.

    `background=True` (pre-warming) routes both part-calls through the LLM
    gate's low-priority lane: capped concurrency, and always behind any
    interactive caller — a user's "Generate PRD" click is never queued
    behind warm work.

    `human_only=True` generates only the human PRD (Part A), skipping the
    implementation-spec — see `_generate_2part`.
    """
    logger.info(
        "PRD generation starting prd_id=%s brief_id=%s insight_index=%s "
        "priority=%s scope=%s",
        prd_id,
        brief_id,
        insight_index,
        "background" if background else "interactive",
        "human_only" if human_only else "2part",
    )
    try:
        await _generate_2part(
            prd_id, brief_id, insight_index, background, human_only=human_only
        )
        logger.info("PRD generation succeeded prd_id=%s", prd_id)
    except Exception as exc:
        msg = f"{type(exc).__name__}: {exc}"
        logger.exception("PRD generation failed prd_id=%s", prd_id)
        fail_prd(prd_id, msg)


def _top_insight_indices(insights: list, count: int) -> list[int]:
    """Original indices of the `count` insights a user is likeliest to open:
    the LLM-flagged headline insight first, then by confidence descending —
    the same hero-selection order the brief UI renders."""
    ranked = sorted(
        range(len(insights)),
        key=lambda i: (
            not bool((insights[i] or {}).get("is_headline")),
            -float((insights[i] or {}).get("confidence") or 0.0),
        ),
    )
    return ranked[:count]


async def _warm_one_prd(brief_id: int, insight_index: int, title: str) -> None:
    """Warm a single insight's human PRD as a multi-agent run.

    Mints a run_id and stamps it on the PRD row so the multi-agent "Generate
    PRD" path dedupes against this warm run instead of restarting it (see
    routes/multi_agent.find_existing_prd guard). Generates the human PRD only
    (Part A) — the prefetch's job is to have the human-readable PRD ready, not
    the implementation spec. Dedup-guarded and error-isolated: warming is a
    perf optimization, never a correctness requirement.
    """
    from app.prompts import PRD_TEMPLATE_VERSION

    try:
        if find_existing_prd(brief_id, insight_index, variant=PRD_VARIANT):
            return
        run_id = str(uuid.uuid4())
        prd_id = start_prd(
            brief_id=brief_id,
            insight_index=insight_index,
            title=title,
            template_version=PRD_TEMPLATE_VERSION,
            variant=PRD_VARIANT,
            run_id=run_id,
        )
        logger.info(
            "Warming PRD prd_id=%s brief_id=%s insight_index=%s run_id=%s",
            prd_id, brief_id, insight_index, run_id,
        )
        await generate_prd(
            prd_id, brief_id, insight_index, background=True, human_only=True
        )
    except Exception:  # noqa: BLE001 — warming is best-effort
        logger.exception(
            "PRD warming failed brief_id=%s insight_index=%s",
            brief_id, insight_index,
        )


async def warm_prds_for_brief(brief: dict) -> None:
    """Pre-generate human PRDs for the top insights of a freshly-saved brief.

    Fans out one warm task per insight (concurrently, rather than sequentially)
    so insight N's PRD never waits on insight N-1's to finish at the task level.
    Each warm runs in the LLM gate's BACKGROUND lane (see app.llm._PriorityGate),
    which still bounds in-flight warm model-calls (bg_cap, default 1) and always
    yields to interactive callers — so a user's "Generate PRD" click is never
    queued behind warming, and the small prod box isn't flooded. Each warm
    dedupes against existing rows, so a brief that already warmed — or an insight
    the user already generated — is skipped.

    Per-insight work (human PRD only + run_id stamping) lives in `_warm_one_prd`.
    """
    count = settings.prd_warm_count
    if count <= 0:
        return
    brief_id = brief.get("id")
    insights = brief.get("insights") or []
    if not brief_id or not insights:
        return

    indices = _top_insight_indices(insights, count)
    started = time.perf_counter()
    await asyncio.gather(
        *(
            _warm_one_prd(
                brief_id, i, (insights[i] or {}).get("title") or f"Insight #{i + 1}"
            )
            for i in indices
        )
    )
    # Single grep-able summary for onboarding-latency measurement: how long the
    # full human-PRD warm took for this brief (background-lane, bg_cap-gated).
    logger.info(
        "warm_prds_for_brief completed: %d insight(s) in %.1fs brief_id=%s",
        len(indices), time.perf_counter() - started, brief_id,
    )
