"""Report grounding for chat follow-ups — the "REPORT IN THIS CHAT" block.

A generated report is the biggest thing a chat turn ever produces, and the
turn after it is almost always about it: "explain more on recommendations
point 1", "which accounts drove theme 2?", "where did that number come from?".
Until now the only route back to the content was the conversation history, and
that route is lossy by design — `app.prompt_history.clamp_turn_text` caps every
folded turn at 4k characters so a report carrying base64 charts cannot 400 the
rest of the thread. For a report that budget is spent on the run line, the
executive summary and the sources block; the recommendations are at the BOTTOM
of the document and never survived the clamp. The model was asked about a
section it had never been shown.

So the report is loaded as its own grounding block instead of being scavenged
from history — the same shape as `app.prd_context`, for the same reason: a
document the user is looking at has to be IN the prompt, whole, not sampled
from the transcript. Capture already stores it with the `conversation_id` it
was generated in (see app/report_capture.py), so the chat room is the key.

Best-effort by construction: no conversation, no captured report, a foreign
tenant, or any read error collapses to an empty string and the ask answers
exactly as it did before.
"""
from __future__ import annotations

import logging

from app.prompt_history import html_to_text

logger = logging.getLogger(__name__)

# The block is the report's VISIBLE TEXT (markup stripped), not its HTML: a
# report document is mostly stylesheet and layout, and the model needs the
# findings. ~30k chars ≈ 7.5k tokens, which comfortably holds a full VoC or
# competitive-intelligence report — long enough that the recommendations at the
# end are always present, which is the entire point of this module.
_REPORT_CAP = 30_000

_HEADER = (
    "=== REPORT IN THIS CHAT ===\n"
    "This report was generated in this conversation and the user is looking at "
    "it. Questions about \"the report\", \"your recommendations\", a numbered "
    "point, a theme, a section, or any finding refer to THIS document — answer "
    "from it, quote its own wording and figures, and say so plainly when it "
    "does not cover what was asked. Do not go looking for the underlying "
    "tickets, calls or channels to re-derive an answer the report already "
    "states.\n"
)


def _cap(text: str) -> str:
    text = (text or "").strip()
    if len(text) <= _REPORT_CAP:
        return text
    return text[:_REPORT_CAP] + "\n[… report truncated]"


def build_report_context(
    company_id: str | None, conversation_id: int | None
) -> str:
    """Render the grounding block for the latest report captured in this chat,
    or '' when there is none (or it can't be read).

    The LATEST report only. A thread can accumulate several, but a follow-up
    points at the one that was just produced, and stacking every report a long
    thread ever generated would crowd out the corpus and KG grounding that the
    same answer still needs.
    """
    if not company_id or not conversation_id:
        return ""
    try:
        from app.db import latest_report_for_conversation

        row = latest_report_for_conversation(conversation_id, company_id)
        if not row:
            return ""
        body = _cap(html_to_text(row.get("html") or ""))
        if not body:
            return ""
        lines = [_HEADER, f"## {row.get('title') or 'Report'}"]
        if row.get("skill"):
            lines.append(f"Generated by the '{row['skill']}' skill.")
        if row.get("question"):
            lines.append(f"Originally asked: {row['question']}")
        lines.append(body)
        return "\n".join(lines)
    except Exception:  # noqa: BLE001 — grounding must never break the answer
        logger.exception(
            "report context unavailable for company=%s conversation=%s",
            company_id,
            conversation_id,
        )
        return ""
