-- Flip identity columns from `generated always` to `generated by default`
-- so the backfill (PR #6) can insert with explicit IDs from SQLite,
-- preserving every row's PK across the cutover. Existing identity
-- sequences are preserved — `by default` still auto-generates IDs when
-- none is supplied.
--
-- After backfill, the sequences will need to be advanced past the
-- max(id) of each table so future inserts don't collide. The backfill
-- script handles that with `setval(pg_get_serial_sequence(...), ...)`.

alter table briefs       alter column id set generated by default;
alter table prds         alter column id set generated by default;
alter table evidences    alter column id set generated by default;
alter table ask_log      alter column id set generated by default;
alter table cached_asks  alter column id set generated by default;
