-- Multi-Agent documents table: stores QA test cases, technical design,
-- risk analysis, and traceability matrix documents generated by the
-- multi-agent orchestrator.

CREATE TABLE IF NOT EXISTS multi_agent_docs (
    id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    brief_id    BIGINT NOT NULL,
    insight_index INT NOT NULL,
    prd_id      BIGINT,
    doc_type    TEXT NOT NULL CHECK (doc_type IN (
        'qa_test_cases', 'technical_design', 'risk_analysis', 'traceability_matrix'
    )),
    title       TEXT NOT NULL DEFAULT '',
    payload_md  TEXT NOT NULL DEFAULT '',
    status      TEXT NOT NULL DEFAULT 'generating' CHECK (status IN (
        'generating', 'ready', 'failed', 'invalidated'
    )),
    error       TEXT,
    run_id      TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Index for polling by run_id (multi-agent orchestrator status checks).
CREATE INDEX IF NOT EXISTS idx_multi_agent_docs_run_id ON multi_agent_docs(run_id);

-- Index for dedup lookups (find_existing_doc).
CREATE INDEX IF NOT EXISTS idx_multi_agent_docs_lookup
    ON multi_agent_docs(brief_id, insight_index, doc_type, status);

-- Auto-update updated_at on row change.
CREATE OR REPLACE FUNCTION update_multi_agent_docs_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_multi_agent_docs_updated_at
    BEFORE UPDATE ON multi_agent_docs
    FOR EACH ROW
    EXECUTE FUNCTION update_multi_agent_docs_updated_at();

-- RLS: rows are accessed server-side (service_role key), no direct
-- browser access. Enable RLS but allow service_role full access.
ALTER TABLE multi_agent_docs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "service_role_full_access" ON multi_agent_docs
    FOR ALL
    USING (true)
    WITH CHECK (true);
